---
# $schema=https://json.schemastore.org/chart.json
apiVersion: v2
name: repo-guardian
description: GitHub App that automates repository onboarding and compliance
type: application
version: 2.0.0-rc.1
appVersion: "2.0.0-rc.1"
