// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_installations.sql

package sqlcdb

import (
	"context"
	"time"
)

const aPIInstallations = `-- name: APIInstallations :many

SELECT i.installation_id, i.org, i.suspended_at, i.removed_at, i.rate_limit, i.rate_remaining, i.rate_reset_at, i.rate_observed_at
FROM (SELECT installation_id, account_login::text AS org, suspended_at, removed_at, rate_limit, rate_remaining,
             rate_reset_at, rate_observed_at
      FROM installations) i
WHERE ($1::bool OR lower(i.org) = ANY ($2::text[]))
  AND (NOT $3::bool OR i.installation_id > $4::bigint)
ORDER BY i.installation_id
LIMIT $5
`

type APIInstallationsParams struct {
	ScopeAll  bool
	ScopeOrgs []string
	HasAfter  bool
	AfterID   int64
	PageLimit int32
}

type APIInstallationsRow struct {
	InstallationID int64
	Org            string
	SuspendedAt    *time.Time
	RemovedAt      *time.Time
	RateLimit      *int32
	RateRemaining  *int32
	RateResetAt    *time.Time
	RateObservedAt *time.Time
}

// API installations (DESIGN-0027, IMPL-0025 Phase 15), scoped by the
// account login, which is the org. Scoping as in api_summary.sql.
func (q *Queries) APIInstallations(ctx context.Context, arg APIInstallationsParams) ([]APIInstallationsRow, error) {
	rows, err := q.db.Query(ctx, aPIInstallations,
		arg.ScopeAll,
		arg.ScopeOrgs,
		arg.HasAfter,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []APIInstallationsRow
	for rows.Next() {
		var i APIInstallationsRow
		if err := rows.Scan(
			&i.InstallationID,
			&i.Org,
			&i.SuspendedAt,
			&i.RemovedAt,
			&i.RateLimit,
			&i.RateRemaining,
			&i.RateResetAt,
			&i.RateObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
