// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_rules.sql

package sqlcdb

import (
	"context"
)

const aPIOrgNotApplicable = `-- name: APIOrgNotApplicable :many
SELECT coalesce(f.reason, '')::text AS reason, count(*)::int AS findings
FROM findings f
JOIN repositories r ON r.id = f.repository_id
WHERE r.active AND f.status = 'not_applicable' AND lower(r.org) = lower($1::text)
  AND ($2::bool OR lower(r.org) = ANY ($3::text[]))
GROUP BY f.reason
ORDER BY findings DESC, reason
`

type APIOrgNotApplicableParams struct {
	Org       string
	ScopeAll  bool
	ScopeOrgs []string
}

type APIOrgNotApplicableRow struct {
	Reason   string
	Findings int32
}

// Not-applicable findings in one org by reason.
func (q *Queries) APIOrgNotApplicable(ctx context.Context, arg APIOrgNotApplicableParams) ([]APIOrgNotApplicableRow, error) {
	rows, err := q.db.Query(ctx, aPIOrgNotApplicable, arg.Org, arg.ScopeAll, arg.ScopeOrgs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []APIOrgNotApplicableRow
	for rows.Next() {
		var i APIOrgNotApplicableRow
		if err := rows.Scan(&i.Reason, &i.Findings); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aPIOrgRepositories = `-- name: APIOrgRepositories :many
SELECT r.org::text AS org, r.active, coalesce(r.park_reason, '')::text AS park_reason, count(*)::int AS repositories
FROM repositories r
WHERE ($1::bool OR lower(r.org) = ANY ($2::text[]))
  AND ($3::text IS NULL OR lower(r.org) = lower($3::text))
GROUP BY r.org, r.active, r.park_reason
ORDER BY lower(r.org), r.active DESC, park_reason
`

type APIOrgRepositoriesParams struct {
	ScopeAll  bool
	ScopeOrgs []string
	Org       *string
}

type APIOrgRepositoriesRow struct {
	Org          string
	Active       bool
	ParkReason   string
	Repositories int32
}

// Repositories in scope per org by active state and park reason.
func (q *Queries) APIOrgRepositories(ctx context.Context, arg APIOrgRepositoriesParams) ([]APIOrgRepositoriesRow, error) {
	rows, err := q.db.Query(ctx, aPIOrgRepositories, arg.ScopeAll, arg.ScopeOrgs, arg.Org)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []APIOrgRepositoriesRow
	for rows.Next() {
		var i APIOrgRepositoriesRow
		if err := rows.Scan(
			&i.Org,
			&i.Active,
			&i.ParkReason,
			&i.Repositories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aPIRuleReasons = `-- name: APIRuleReasons :many

SELECT coalesce(f.reason, '')::text AS reason, count(*)::int AS findings
FROM findings f
JOIN repositories r ON r.id = f.repository_id
WHERE r.active AND f.rule_kind = $1 AND f.rule_name = $2
  AND f.status IN ('non_compliant', 'not_applicable') AND f.reason IS NOT NULL
  AND ($3::bool OR lower(r.org) = ANY ($4::text[]))
GROUP BY f.reason
ORDER BY findings DESC, reason
`

type APIRuleReasonsParams struct {
	RuleKind  string
	RuleName  string
	ScopeAll  bool
	ScopeOrgs []string
}

type APIRuleReasonsRow struct {
	Reason   string
	Findings int32
}

// API rule and org drill-downs (DESIGN-0027, IMPL-0025 Phase 15). The
// per-(org, rule) counts come from the shared ComplianceByRule query in
// compliance.sql; these add what it does not carry. Scoping as in
// api_summary.sql.
// Why one rule is failing or not applicable in scope, most common first.
func (q *Queries) APIRuleReasons(ctx context.Context, arg APIRuleReasonsParams) ([]APIRuleReasonsRow, error) {
	rows, err := q.db.Query(ctx, aPIRuleReasons,
		arg.RuleKind,
		arg.RuleName,
		arg.ScopeAll,
		arg.ScopeOrgs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []APIRuleReasonsRow
	for rows.Next() {
		var i APIRuleReasonsRow
		if err := rows.Scan(&i.Reason, &i.Findings); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
