// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_summary.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const aPISummaryFindings = `-- name: APISummaryFindings :one
SELECT count(*) FILTER (WHERE f.status = 'compliant')::int AS compliant,
       count(*) FILTER (WHERE f.status = 'non_compliant')::int AS non_compliant,
       count(*) FILTER (WHERE f.status = 'not_applicable')::int AS not_applicable,
       count(*) FILTER (WHERE f.status = 'unknown')::int AS unknown,
       CASE WHEN count(*) FILTER (WHERE f.status IN ('compliant', 'non_compliant')) = 0 THEN NULL
            ELSE (floor(count(*) FILTER (WHERE f.status = 'compliant') * 1000.0
                        / count(*) FILTER (WHERE f.status IN ('compliant', 'non_compliant'))) / 10)::numeric
       END AS compliant_percent
FROM findings f
JOIN repositories r ON r.id = f.repository_id
WHERE r.active
  AND ($1::bool OR lower(r.org) = ANY ($2::text[]))
`

type APISummaryFindingsParams struct {
	ScopeAll  bool
	ScopeOrgs []string
}

type APISummaryFindingsRow struct {
	Compliant        int32
	NonCompliant     int32
	NotApplicable    int32
	Unknown          int32
	CompliantPercent pgtype.Numeric
}

// Finding counts over active repositories in scope, with the shared
// compliance math (see compliance.sql).
func (q *Queries) APISummaryFindings(ctx context.Context, arg APISummaryFindingsParams) (APISummaryFindingsRow, error) {
	row := q.db.QueryRow(ctx, aPISummaryFindings, arg.ScopeAll, arg.ScopeOrgs)
	var i APISummaryFindingsRow
	err := row.Scan(
		&i.Compliant,
		&i.NonCompliant,
		&i.NotApplicable,
		&i.Unknown,
		&i.CompliantPercent,
	)
	return i, err
}

const aPISummaryOpenPRs = `-- name: APISummaryOpenPRs :many
SELECT r.id, min((f.evidence -> 'pr' ->> 'created_at')::timestamptz)::timestamptz AS created_at
FROM findings f
JOIN repositories r ON r.id = f.repository_id
WHERE r.active AND f.remediation = 'pr_open' AND f.evidence -> 'pr' ->> 'created_at' IS NOT NULL
  AND ($1::bool OR lower(r.org) = ANY ($2::text[]))
GROUP BY r.id
ORDER BY r.id
`

type APISummaryOpenPRsParams struct {
	ScopeAll  bool
	ScopeOrgs []string
}

type APISummaryOpenPRsRow struct {
	ID        int64
	CreatedAt time.Time
}

// One row per open repo-guardian PR (one branch per repository), aged
// by the PR's created_at from its findings' evidence.
func (q *Queries) APISummaryOpenPRs(ctx context.Context, arg APISummaryOpenPRsParams) ([]APISummaryOpenPRsRow, error) {
	rows, err := q.db.Query(ctx, aPISummaryOpenPRs, arg.ScopeAll, arg.ScopeOrgs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []APISummaryOpenPRsRow
	for rows.Next() {
		var i APISummaryOpenPRsRow
		if err := rows.Scan(&i.ID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aPISummaryRepositories = `-- name: APISummaryRepositories :many

SELECT r.active, coalesce(r.park_reason, '')::text AS park_reason, count(*)::int AS repositories
FROM repositories r
WHERE ($1::bool OR lower(r.org) = ANY ($2::text[]))
GROUP BY r.active, r.park_reason
ORDER BY r.active DESC, park_reason
`

type APISummaryRepositoriesParams struct {
	ScopeAll  bool
	ScopeOrgs []string
}

type APISummaryRepositoriesRow struct {
	Active       bool
	ParkReason   string
	Repositories int32
}

// API queries (DESIGN-0027, IMPL-0025 Phase 14). Every api_*.sql query
// is scoped in SQL by the caller's visible orgs with exactly
//
//	(@scope_all::bool OR lower(<alias>.org) = ANY (@scope_orgs::text[]))
//
// scope_orgs is lower-cased and empty scope_orgs with scope_all false
// matches nothing. TestAPIQueries_AreScoped fails on a query without the
// predicate. Unlike compliance.sql, an empty org list never means "all".
// Repositories in scope by active state and park reason.
func (q *Queries) APISummaryRepositories(ctx context.Context, arg APISummaryRepositoriesParams) ([]APISummaryRepositoriesRow, error) {
	rows, err := q.db.Query(ctx, aPISummaryRepositories, arg.ScopeAll, arg.ScopeOrgs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []APISummaryRepositoriesRow
	for rows.Next() {
		var i APISummaryRepositoriesRow
		if err := rows.Scan(&i.Active, &i.ParkReason, &i.Repositories); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
