// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_history.sql

package sqlcdb

import (
	"context"
	"time"
)

const aPIComplianceHistory = `-- name: APIComplianceHistory :many

SELECT s.org, s.rule_kind, s.rule_name, s.snapshot_at, s.compliant, s.non_compliant, s.not_applicable, s.unknown
FROM compliance_snapshots s
WHERE ($1::bool OR lower(s.org) = ANY ($2::text[]))
  AND ($3::text IS NULL OR lower(s.org) = lower($3::text))
  AND ($4::text IS NULL OR s.rule_kind = $4::text)
  AND ($5::text IS NULL OR s.rule_name = $5::text)
  AND ($6::timestamptz IS NULL OR s.snapshot_at >= $6::timestamptz)
  AND ($7::timestamptz IS NULL OR s.snapshot_at < $7::timestamptz)
  AND (NOT $8::bool
       OR (s.snapshot_at, s.org, s.rule_kind, s.rule_name)
          > ($9::timestamptz, $10::text, $11::text, $12::text))
ORDER BY s.snapshot_at, s.org, s.rule_kind, s.rule_name
LIMIT $13
`

type APIComplianceHistoryParams struct {
	ScopeAll        bool
	ScopeOrgs       []string
	Org             *string
	RuleKind        *string
	RuleName        *string
	FromAt          *time.Time
	ToAt            *time.Time
	HasAfter        bool
	AfterSnapshotAt time.Time
	AfterOrg        string
	AfterRuleKind   string
	AfterRuleName   string
	PageLimit       int32
}

// API compliance history (DESIGN-0027, IMPL-0025 Phase 15): stored
// snapshots, oldest first, keyed by (snapshot_at, org, kind, rule).
// Scoping as in api_summary.sql.
func (q *Queries) APIComplianceHistory(ctx context.Context, arg APIComplianceHistoryParams) ([]ComplianceSnapshot, error) {
	rows, err := q.db.Query(ctx, aPIComplianceHistory,
		arg.ScopeAll,
		arg.ScopeOrgs,
		arg.Org,
		arg.RuleKind,
		arg.RuleName,
		arg.FromAt,
		arg.ToAt,
		arg.HasAfter,
		arg.AfterSnapshotAt,
		arg.AfterOrg,
		arg.AfterRuleKind,
		arg.AfterRuleName,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComplianceSnapshot
	for rows.Next() {
		var i ComplianceSnapshot
		if err := rows.Scan(
			&i.Org,
			&i.RuleKind,
			&i.RuleName,
			&i.SnapshotAt,
			&i.Compliant,
			&i.NonCompliant,
			&i.NotApplicable,
			&i.Unknown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
