// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_repositories.sql

package sqlcdb

import (
	"context"
	"time"
)

const aPIRepositories = `-- name: APIRepositories :many

SELECT r.id, r.org, r.name, r.provider_repo_id, r.installation_id, r.active, r.park_reason, r.parked_at,
       r.discovered_at, r.next_due_at, r.last_checked_at, r.last_check_outcome, r.policy_version
FROM repositories r
WHERE ($1::bool OR lower(r.org) = ANY ($2::text[]))
  AND ($3::text IS NULL OR lower(r.org) = lower($3::text))
  AND ($4::bool IS NULL OR r.active = $4::bool)
  AND ($5::text IS NULL OR r.park_reason = $5::text)
  AND ($6::text IS NULL
       OR left(lower(r.name), length($6::text)) = lower($6::text))
  AND (NOT $7::bool OR r.id > $8::bigint)
ORDER BY r.id
LIMIT $9
`

type APIRepositoriesParams struct {
	ScopeAll   bool
	ScopeOrgs  []string
	Org        *string
	Active     *bool
	ParkReason *string
	NamePrefix *string
	HasAfter   bool
	AfterID    int64
	PageLimit  int32
}

type APIRepositoriesRow struct {
	ID               int64
	Org              string
	Name             string
	ProviderRepoID   *int64
	InstallationID   int64
	Active           bool
	ParkReason       *string
	ParkedAt         *time.Time
	DiscoveredAt     time.Time
	NextDueAt        *time.Time
	LastCheckedAt    *time.Time
	LastCheckOutcome string
	PolicyVersion    string
}

// API repositories (DESIGN-0027, IMPL-0025 Phase 15). Scoping as in
// api_summary.sql. Pages are keyed by id.
func (q *Queries) APIRepositories(ctx context.Context, arg APIRepositoriesParams) ([]APIRepositoriesRow, error) {
	rows, err := q.db.Query(ctx, aPIRepositories,
		arg.ScopeAll,
		arg.ScopeOrgs,
		arg.Org,
		arg.Active,
		arg.ParkReason,
		arg.NamePrefix,
		arg.HasAfter,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []APIRepositoriesRow
	for rows.Next() {
		var i APIRepositoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Org,
			&i.Name,
			&i.ProviderRepoID,
			&i.InstallationID,
			&i.Active,
			&i.ParkReason,
			&i.ParkedAt,
			&i.DiscoveredAt,
			&i.NextDueAt,
			&i.LastCheckedAt,
			&i.LastCheckOutcome,
			&i.PolicyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aPIRepository = `-- name: APIRepository :one
SELECT r.id, r.org, r.name, r.provider_repo_id, r.installation_id, r.active, r.park_reason, r.parked_at,
       r.discovered_at, r.next_due_at, r.last_checked_at, r.last_check_outcome, r.policy_version,
       i.account_login, i.suspended_at, i.removed_at, i.rate_limit, i.rate_remaining, i.rate_reset_at, i.rate_observed_at
FROM repositories r
JOIN installations i ON i.installation_id = r.installation_id
WHERE r.id = $1
  AND ($2::bool OR lower(r.org) = ANY ($3::text[]))
`

type APIRepositoryParams struct {
	ID        int64
	ScopeAll  bool
	ScopeOrgs []string
}

type APIRepositoryRow struct {
	ID               int64
	Org              string
	Name             string
	ProviderRepoID   *int64
	InstallationID   int64
	Active           bool
	ParkReason       *string
	ParkedAt         *time.Time
	DiscoveredAt     time.Time
	NextDueAt        *time.Time
	LastCheckedAt    *time.Time
	LastCheckOutcome string
	PolicyVersion    string
	AccountLogin     string
	SuspendedAt      *time.Time
	RemovedAt        *time.Time
	RateLimit        *int32
	RateRemaining    *int32
	RateResetAt      *time.Time
	RateObservedAt   *time.Time
}

// One repository in scope with its installation.
func (q *Queries) APIRepository(ctx context.Context, arg APIRepositoryParams) (APIRepositoryRow, error) {
	row := q.db.QueryRow(ctx, aPIRepository, arg.ID, arg.ScopeAll, arg.ScopeOrgs)
	var i APIRepositoryRow
	err := row.Scan(
		&i.ID,
		&i.Org,
		&i.Name,
		&i.ProviderRepoID,
		&i.InstallationID,
		&i.Active,
		&i.ParkReason,
		&i.ParkedAt,
		&i.DiscoveredAt,
		&i.NextDueAt,
		&i.LastCheckedAt,
		&i.LastCheckOutcome,
		&i.PolicyVersion,
		&i.AccountLogin,
		&i.SuspendedAt,
		&i.RemovedAt,
		&i.RateLimit,
		&i.RateRemaining,
		&i.RateResetAt,
		&i.RateObservedAt,
	)
	return i, err
}
