// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_findings.sql

package sqlcdb

import (
	"context"
	"encoding/json"
	"time"
)

const aPIFindings = `-- name: APIFindings :many

SELECT f.repository_id, r.org, r.name, f.rule_kind, f.rule_name, f.status, f.reason, f.remediation,
       f.evidence, f.status_since, f.last_evaluated_at,
       coalesce(f.remediation = 'pr_open'
                AND (f.evidence -> 'pr' ->> 'created_at')::timestamptz < $1::timestamptz, false)::bool AS pr_stale
FROM findings f
JOIN repositories r ON r.id = f.repository_id
WHERE r.active
  AND ($2::bool OR lower(r.org) = ANY ($3::text[]))
  AND ($4::text IS NULL OR f.status = $4::text)
  AND ($5::text IS NULL OR f.reason = $5::text)
  AND ($6::text IS NULL OR f.remediation = $6::text)
  AND ($7::text IS NULL OR lower(r.org) = lower($7::text))
  AND ($8::text IS NULL OR f.rule_kind = $8::text)
  AND ($9::text IS NULL OR f.rule_name = $9::text)
  AND ($10::timestamptz IS NULL OR f.status_since < $10::timestamptz)
  AND ($11::bool IS NULL
       OR coalesce(f.remediation = 'pr_open'
                   AND (f.evidence -> 'pr' ->> 'created_at')::timestamptz < $1::timestamptz, false)
          = $11::bool)
  AND (NOT $12::bool
       OR (f.repository_id, f.rule_kind, f.rule_name) > ($13::bigint, $14::text, $15::text))
ORDER BY f.repository_id, f.rule_kind, f.rule_name
LIMIT $16
`

type APIFindingsParams struct {
	StaleBefore       time.Time
	ScopeAll          bool
	ScopeOrgs         []string
	Status            *string
	Reason            *string
	Remediation       *string
	Org               *string
	RuleKind          *string
	RuleName          *string
	SinceBefore       *time.Time
	PrStale           *bool
	HasAfter          bool
	AfterRepositoryID int64
	AfterRuleKind     string
	AfterRuleName     string
	PageLimit         int32
}

type APIFindingsRow struct {
	RepositoryID    int64
	Org             string
	Name            string
	RuleKind        string
	RuleName        string
	Status          string
	Reason          *string
	Remediation     string
	Evidence        json.RawMessage
	StatusSince     time.Time
	LastEvaluatedAt time.Time
	PrStale         bool
}

// API findings (DESIGN-0027, IMPL-0025 Phase 15). Scoping as in
// api_summary.sql. Pages are keyed by the findings primary key.
//
// pr_stale: the finding's repo-guardian PR is open and was created
// before @stale_before (now minus stale_after).
func (q *Queries) APIFindings(ctx context.Context, arg APIFindingsParams) ([]APIFindingsRow, error) {
	rows, err := q.db.Query(ctx, aPIFindings,
		arg.StaleBefore,
		arg.ScopeAll,
		arg.ScopeOrgs,
		arg.Status,
		arg.Reason,
		arg.Remediation,
		arg.Org,
		arg.RuleKind,
		arg.RuleName,
		arg.SinceBefore,
		arg.PrStale,
		arg.HasAfter,
		arg.AfterRepositoryID,
		arg.AfterRuleKind,
		arg.AfterRuleName,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []APIFindingsRow
	for rows.Next() {
		var i APIFindingsRow
		if err := rows.Scan(
			&i.RepositoryID,
			&i.Org,
			&i.Name,
			&i.RuleKind,
			&i.RuleName,
			&i.Status,
			&i.Reason,
			&i.Remediation,
			&i.Evidence,
			&i.StatusSince,
			&i.LastEvaluatedAt,
			&i.PrStale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aPIOldestFailures = `-- name: APIOldestFailures :many
SELECT f.repository_id, r.org, r.name, f.rule_kind, f.rule_name, f.status, f.reason, f.remediation,
       f.evidence, f.status_since, f.last_evaluated_at,
       coalesce(f.remediation = 'pr_open'
                AND (f.evidence -> 'pr' ->> 'created_at')::timestamptz < $1::timestamptz, false)::bool AS pr_stale
FROM findings f
JOIN repositories r ON r.id = f.repository_id
WHERE r.active AND f.status = 'non_compliant' AND f.rule_kind = $2 AND f.rule_name = $3
  AND ($4::bool OR lower(r.org) = ANY ($5::text[]))
ORDER BY f.status_since, f.repository_id
LIMIT $6
`

type APIOldestFailuresParams struct {
	StaleBefore time.Time
	RuleKind    string
	RuleName    string
	ScopeAll    bool
	ScopeOrgs   []string
	PageLimit   int32
}

type APIOldestFailuresRow struct {
	RepositoryID    int64
	Org             string
	Name            string
	RuleKind        string
	RuleName        string
	Status          string
	Reason          *string
	Remediation     string
	Evidence        json.RawMessage
	StatusSince     time.Time
	LastEvaluatedAt time.Time
	PrStale         bool
}

// One rule's longest-failing findings in scope.
func (q *Queries) APIOldestFailures(ctx context.Context, arg APIOldestFailuresParams) ([]APIOldestFailuresRow, error) {
	rows, err := q.db.Query(ctx, aPIOldestFailures,
		arg.StaleBefore,
		arg.RuleKind,
		arg.RuleName,
		arg.ScopeAll,
		arg.ScopeOrgs,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []APIOldestFailuresRow
	for rows.Next() {
		var i APIOldestFailuresRow
		if err := rows.Scan(
			&i.RepositoryID,
			&i.Org,
			&i.Name,
			&i.RuleKind,
			&i.RuleName,
			&i.Status,
			&i.Reason,
			&i.Remediation,
			&i.Evidence,
			&i.StatusSince,
			&i.LastEvaluatedAt,
			&i.PrStale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aPIRepositoryFindings = `-- name: APIRepositoryFindings :many
SELECT f.repository_id, r.org, r.name, f.rule_kind, f.rule_name, f.status, f.reason, f.remediation,
       f.evidence, f.status_since, f.last_evaluated_at,
       coalesce(f.remediation = 'pr_open'
                AND (f.evidence -> 'pr' ->> 'created_at')::timestamptz < $1::timestamptz, false)::bool AS pr_stale
FROM findings f
JOIN repositories r ON r.id = f.repository_id
WHERE f.repository_id = $2
  AND ($3::bool OR lower(r.org) = ANY ($4::text[]))
ORDER BY f.rule_kind, f.rule_name
`

type APIRepositoryFindingsParams struct {
	StaleBefore  time.Time
	RepositoryID int64
	ScopeAll     bool
	ScopeOrgs    []string
}

type APIRepositoryFindingsRow struct {
	RepositoryID    int64
	Org             string
	Name            string
	RuleKind        string
	RuleName        string
	Status          string
	Reason          *string
	Remediation     string
	Evidence        json.RawMessage
	StatusSince     time.Time
	LastEvaluatedAt time.Time
	PrStale         bool
}

// Every finding on one repository in scope.
func (q *Queries) APIRepositoryFindings(ctx context.Context, arg APIRepositoryFindingsParams) ([]APIRepositoryFindingsRow, error) {
	rows, err := q.db.Query(ctx, aPIRepositoryFindings,
		arg.StaleBefore,
		arg.RepositoryID,
		arg.ScopeAll,
		arg.ScopeOrgs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []APIRepositoryFindingsRow
	for rows.Next() {
		var i APIRepositoryFindingsRow
		if err := rows.Scan(
			&i.RepositoryID,
			&i.Org,
			&i.Name,
			&i.RuleKind,
			&i.RuleName,
			&i.Status,
			&i.Reason,
			&i.Remediation,
			&i.Evidence,
			&i.StatusSince,
			&i.LastEvaluatedAt,
			&i.PrStale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
