// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_events.sql

package sqlcdb

import (
	"context"
	"encoding/json"
	"time"
)

const aPIRepositoryEvents = `-- name: APIRepositoryEvents :many

SELECT e.source, e.id, e.occurred_at, coalesce(e.rule_kind, '')::text AS rule_kind, coalesce(e.rule_name, '')::text AS rule_name, e.from_status, e.to_status,
       e.from_reason, e.to_reason, e.from_remediation, e.to_remediation, e.kind, e.detail
FROM (
    SELECT 'finding'::text AS source, fe.id, fe.occurred_at, fe.rule_kind, fe.rule_name,
           fe.from_status, fe.to_status, fe.from_reason, fe.to_reason, fe.from_remediation, fe.to_remediation,
           NULL::text AS kind, NULL::jsonb AS detail
    FROM finding_events fe
    WHERE fe.repository_id = $1
    UNION ALL
    SELECT 'repository'::text, re.id, re.occurred_at, NULL::text, NULL::text,
           NULL::text, NULL::text, NULL::text, NULL::text, NULL::text, NULL::text,
           re.kind, re.detail
    FROM repository_events re
    WHERE re.repository_id = $1
) e
JOIN repositories r ON r.id = $1
WHERE ($2::bool OR lower(r.org) = ANY ($3::text[]))
  AND (NOT $4::bool
       OR (e.occurred_at, e.source, e.id) < ($5::timestamptz, $6::text, $7::bigint))
ORDER BY e.occurred_at DESC, e.source DESC, e.id DESC
LIMIT $8
`

type APIRepositoryEventsParams struct {
	RepositoryID    int64
	ScopeAll        bool
	ScopeOrgs       []string
	HasAfter        bool
	AfterOccurredAt time.Time
	AfterSource     string
	AfterID         int64
	PageLimit       int32
}

type APIRepositoryEventsRow struct {
	Source          string
	ID              int64
	OccurredAt      time.Time
	RuleKind        string
	RuleName        string
	FromStatus      *string
	ToStatus        *string
	FromReason      *string
	ToReason        *string
	FromRemediation *string
	ToRemediation   *string
	Kind            *string
	Detail          json.RawMessage
}

// API timeline (DESIGN-0027, IMPL-0025 Phase 15): finding and
// repository events merged with UNION ALL, newest first, keyed by
// (occurred_at, source, id). Scoping as in api_summary.sql.
func (q *Queries) APIRepositoryEvents(ctx context.Context, arg APIRepositoryEventsParams) ([]APIRepositoryEventsRow, error) {
	rows, err := q.db.Query(ctx, aPIRepositoryEvents,
		arg.RepositoryID,
		arg.ScopeAll,
		arg.ScopeOrgs,
		arg.HasAfter,
		arg.AfterOccurredAt,
		arg.AfterSource,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []APIRepositoryEventsRow
	for rows.Next() {
		var i APIRepositoryEventsRow
		if err := rows.Scan(
			&i.Source,
			&i.ID,
			&i.OccurredAt,
			&i.RuleKind,
			&i.RuleName,
			&i.FromStatus,
			&i.ToStatus,
			&i.FromReason,
			&i.ToReason,
			&i.FromRemediation,
			&i.ToRemediation,
			&i.Kind,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
