// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_checks.sql

package sqlcdb

import (
	"context"
	"time"
)

const aPIRepositoryChecks = `-- name: APIRepositoryChecks :many

SELECT c.id, c.trigger, c.outcome, c.policy_version, c.started_at, c.finished_at, c.error
FROM checks c
JOIN repositories r ON r.id = c.repository_id
WHERE c.repository_id = $1
  AND ($2::bool OR lower(r.org) = ANY ($3::text[]))
  AND (NOT $4::bool OR c.id < $5::bigint)
ORDER BY c.id DESC
LIMIT $6
`

type APIRepositoryChecksParams struct {
	RepositoryID int64
	ScopeAll     bool
	ScopeOrgs    []string
	HasAfter     bool
	AfterID      int64
	PageLimit    int32
}

type APIRepositoryChecksRow struct {
	ID            int64
	Trigger       string
	Outcome       string
	PolicyVersion string
	StartedAt     time.Time
	FinishedAt    *time.Time
	Error         *string
}

// API checks (DESIGN-0027, IMPL-0025 Phase 15). Scoping as in
// api_summary.sql. Pages are keyed by id, newest first.
func (q *Queries) APIRepositoryChecks(ctx context.Context, arg APIRepositoryChecksParams) ([]APIRepositoryChecksRow, error) {
	rows, err := q.db.Query(ctx, aPIRepositoryChecks,
		arg.RepositoryID,
		arg.ScopeAll,
		arg.ScopeOrgs,
		arg.HasAfter,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []APIRepositoryChecksRow
	for rows.Next() {
		var i APIRepositoryChecksRow
		if err := rows.Scan(
			&i.ID,
			&i.Trigger,
			&i.Outcome,
			&i.PolicyVersion,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
