// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checks.sql

package sqlcdb

import (
	"context"
	"encoding/json"
	"time"
)

const finalizeCheck = `-- name: FinalizeCheck :one
INSERT INTO checks (repository_id, check_key, trigger, outcome, error, policy_version, started_at, finished_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (check_key) DO UPDATE
SET outcome = excluded.outcome,
    error = excluded.error,
    pending_result = NULL,
    policy_version = excluded.policy_version,
    finished_at = excluded.finished_at
WHERE checks.outcome = 'pending'
RETURNING id
`

type FinalizeCheckParams struct {
	RepositoryID  int64
	CheckKey      string
	Trigger       string
	Outcome       string
	Error         *string
	PolicyVersion string
	StartedAt     time.Time
	FinishedAt    *time.Time
}

// Inserts the final row, or finalizes a staged one. Returns no row when
// the key is already final.
func (q *Queries) FinalizeCheck(ctx context.Context, arg FinalizeCheckParams) (int64, error) {
	row := q.db.QueryRow(ctx, finalizeCheck,
		arg.RepositoryID,
		arg.CheckKey,
		arg.Trigger,
		arg.Outcome,
		arg.Error,
		arg.PolicyVersion,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lockCheckByKey = `-- name: LockCheckByKey :one
SELECT id, repository_id, outcome, pending_result FROM checks
WHERE check_key = $1
FOR UPDATE
`

type LockCheckByKeyRow struct {
	ID            int64
	RepositoryID  int64
	Outcome       string
	PendingResult json.RawMessage
}

func (q *Queries) LockCheckByKey(ctx context.Context, checkKey string) (LockCheckByKeyRow, error) {
	row := q.db.QueryRow(ctx, lockCheckByKey, checkKey)
	var i LockCheckByKeyRow
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Outcome,
		&i.PendingResult,
	)
	return i, err
}

const pruneChecks = `-- name: PruneChecks :execrows
DELETE FROM checks WHERE finished_at < $1 AND outcome <> 'pending'
`

func (q *Queries) PruneChecks(ctx context.Context, finishedAt *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, pruneChecks, finishedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stageCheck = `-- name: StageCheck :exec
INSERT INTO checks (repository_id, check_key, trigger, outcome, pending_result, policy_version, started_at)
VALUES ($1, $2, $3, 'pending', $4, $5, $6)
ON CONFLICT (check_key) DO UPDATE
SET pending_result = excluded.pending_result
WHERE checks.outcome = 'pending'
`

type StageCheckParams struct {
	RepositoryID  int64
	CheckKey      string
	Trigger       string
	PendingResult json.RawMessage
	PolicyVersion string
	StartedAt     time.Time
}

func (q *Queries) StageCheck(ctx context.Context, arg StageCheckParams) error {
	_, err := q.db.Exec(ctx, stageCheck,
		arg.RepositoryID,
		arg.CheckKey,
		arg.Trigger,
		arg.PendingResult,
		arg.PolicyVersion,
		arg.StartedAt,
	)
	return err
}
