// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compliance.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const complianceByRule = `-- name: ComplianceByRule :many

SELECT r.org, f.rule_kind, f.rule_name,
       count(*) FILTER (WHERE f.status = 'compliant')::int AS compliant,
       count(*) FILTER (WHERE f.status = 'non_compliant')::int AS non_compliant,
       count(*) FILTER (WHERE f.status = 'not_applicable')::int AS not_applicable,
       count(*) FILTER (WHERE f.status = 'unknown')::int AS unknown,
       CASE WHEN count(*) FILTER (WHERE f.status IN ('compliant', 'non_compliant')) = 0 THEN NULL
            ELSE (floor(count(*) FILTER (WHERE f.status = 'compliant') * 1000.0
                        / count(*) FILTER (WHERE f.status IN ('compliant', 'non_compliant'))) / 10)::numeric
       END AS compliant_percent
FROM findings f
JOIN repositories r ON r.id = f.repository_id
WHERE r.active
  AND (cardinality($1::text[]) = 0 OR lower(r.org) = ANY ($1::text[]))
GROUP BY r.org, f.rule_kind, f.rule_name
ORDER BY r.org, f.rule_kind, f.rule_name
`

type ComplianceByRuleRow struct {
	Org              string
	RuleKind         string
	RuleName         string
	Compliant        int32
	NonCompliant     int32
	NotApplicable    int32
	Unknown          int32
	CompliantPercent pgtype.Numeric
}

// The shared compliance query (DESIGN-0025, IMPL-0025 Phase 8). The
// report, the snapshot writer and the API all read these counts, so the
// three can never disagree about a percentage.
//
// compliant_percent = compliant / (compliant + non_compliant) over active
// repositories, floored (never rounded) to one decimal: 999 of 1000 reads
// 99.9, not 100. not_applicable and unknown are reported beside it, never
// in it. An empty denominator is NULL: a rule that applies nowhere is
// unmeasured, not 100% compliant.
//
// orgs scopes the result; lower-case the names, an empty array means every
// org.
func (q *Queries) ComplianceByRule(ctx context.Context, orgs []string) ([]ComplianceByRuleRow, error) {
	rows, err := q.db.Query(ctx, complianceByRule, orgs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComplianceByRuleRow
	for rows.Next() {
		var i ComplianceByRuleRow
		if err := rows.Scan(
			&i.Org,
			&i.RuleKind,
			&i.RuleName,
			&i.Compliant,
			&i.NonCompliant,
			&i.NotApplicable,
			&i.Unknown,
			&i.CompliantPercent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failingFindings = `-- name: FailingFindings :many
SELECT r.installation_id, r.org, r.name, f.rule_kind, f.rule_name, f.reason, f.remediation,
       f.status_since, coalesce(f.evidence -> 'pr' ->> 'url', '')::text AS pr_url
FROM findings f
JOIN repositories r ON r.id = f.repository_id
WHERE r.active AND f.status = 'non_compliant'
  AND (cardinality($1::text[]) = 0 OR lower(r.org) = ANY ($1::text[]))
ORDER BY r.org, f.rule_name, r.name, f.rule_kind
`

type FailingFindingsRow struct {
	InstallationID int64
	Org            string
	Name           string
	RuleKind       string
	RuleName       string
	Reason         *string
	Remediation    string
	StatusSince    time.Time
	PrUrl          string
}

// Non-compliant findings on active repositories, ordered by org, rule,
// then repository so an unchanged database renders an identical report.
func (q *Queries) FailingFindings(ctx context.Context, orgs []string) ([]FailingFindingsRow, error) {
	rows, err := q.db.Query(ctx, failingFindings, orgs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FailingFindingsRow
	for rows.Next() {
		var i FailingFindingsRow
		if err := rows.Scan(
			&i.InstallationID,
			&i.Org,
			&i.Name,
			&i.RuleKind,
			&i.RuleName,
			&i.Reason,
			&i.Remediation,
			&i.StatusSince,
			&i.PrUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestComplianceSnapshots = `-- name: LatestComplianceSnapshots :many
SELECT DISTINCT ON (org, rule_kind, rule_name)
       org, rule_kind, rule_name, snapshot_at, compliant, non_compliant, not_applicable, unknown
FROM compliance_snapshots
WHERE cardinality($1::text[]) = 0 OR lower(org) = ANY ($1::text[])
ORDER BY org, rule_kind, rule_name, snapshot_at DESC
`

// The most recent snapshot per (org, kind, rule): what the report's
// trend compares against.
func (q *Queries) LatestComplianceSnapshots(ctx context.Context, orgs []string) ([]ComplianceSnapshot, error) {
	rows, err := q.db.Query(ctx, latestComplianceSnapshots, orgs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComplianceSnapshot
	for rows.Next() {
		var i ComplianceSnapshot
		if err := rows.Scan(
			&i.Org,
			&i.RuleKind,
			&i.RuleName,
			&i.SnapshotAt,
			&i.Compliant,
			&i.NonCompliant,
			&i.NotApplicable,
			&i.Unknown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
