// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlcdb

import (
	"context"
	"encoding/json"
	"time"
)

const insertFindingEvent = `-- name: InsertFindingEvent :exec
INSERT INTO finding_events (
    repository_id, rule_kind, rule_name, check_id,
    from_status, to_status, from_reason, to_reason,
    from_remediation, to_remediation, evidence, policy_version, occurred_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type InsertFindingEventParams struct {
	RepositoryID    int64
	RuleKind        string
	RuleName        string
	CheckID         *int64
	FromStatus      *string
	ToStatus        *string
	FromReason      *string
	ToReason        *string
	FromRemediation *string
	ToRemediation   *string
	Evidence        json.RawMessage
	PolicyVersion   string
	OccurredAt      time.Time
}

func (q *Queries) InsertFindingEvent(ctx context.Context, arg InsertFindingEventParams) error {
	_, err := q.db.Exec(ctx, insertFindingEvent,
		arg.RepositoryID,
		arg.RuleKind,
		arg.RuleName,
		arg.CheckID,
		arg.FromStatus,
		arg.ToStatus,
		arg.FromReason,
		arg.ToReason,
		arg.FromRemediation,
		arg.ToRemediation,
		arg.Evidence,
		arg.PolicyVersion,
		arg.OccurredAt,
	)
	return err
}

const insertRepositoryEvent = `-- name: InsertRepositoryEvent :exec
INSERT INTO repository_events (repository_id, kind, detail) VALUES ($1, $2, $3)
`

type InsertRepositoryEventParams struct {
	RepositoryID int64
	Kind         string
	Detail       json.RawMessage
}

func (q *Queries) InsertRepositoryEvent(ctx context.Context, arg InsertRepositoryEventParams) error {
	_, err := q.db.Exec(ctx, insertRepositoryEvent, arg.RepositoryID, arg.Kind, arg.Detail)
	return err
}

const listFindingEventsByCheck = `-- name: ListFindingEventsByCheck :many
SELECT id, repository_id, rule_kind, rule_name, check_id, from_status, to_status, from_reason, to_reason, from_remediation, to_remediation, evidence, policy_version, occurred_at FROM finding_events WHERE check_id = $1 ORDER BY id
`

func (q *Queries) ListFindingEventsByCheck(ctx context.Context, checkID *int64) ([]FindingEvent, error) {
	rows, err := q.db.Query(ctx, listFindingEventsByCheck, checkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindingEvent
	for rows.Next() {
		var i FindingEvent
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.RuleKind,
			&i.RuleName,
			&i.CheckID,
			&i.FromStatus,
			&i.ToStatus,
			&i.FromReason,
			&i.ToReason,
			&i.FromRemediation,
			&i.ToRemediation,
			&i.Evidence,
			&i.PolicyVersion,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
