// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: findings.sql

package sqlcdb

import (
	"context"
	"encoding/json"
	"time"
)

const deleteFinding = `-- name: DeleteFinding :exec
DELETE FROM findings WHERE repository_id = $1 AND rule_kind = $2 AND rule_name = $3
`

type DeleteFindingParams struct {
	RepositoryID int64
	RuleKind     string
	RuleName     string
}

func (q *Queries) DeleteFinding(ctx context.Context, arg DeleteFindingParams) error {
	_, err := q.db.Exec(ctx, deleteFinding, arg.RepositoryID, arg.RuleKind, arg.RuleName)
	return err
}

const lockFindings = `-- name: LockFindings :many
SELECT repository_id, rule_kind, rule_name, status, reason, remediation, evidence, evidence_version, status_since, last_evaluated_at, policy_version FROM findings
WHERE repository_id = $1
ORDER BY rule_kind, rule_name
FOR UPDATE
`

func (q *Queries) LockFindings(ctx context.Context, repositoryID int64) ([]Finding, error) {
	rows, err := q.db.Query(ctx, lockFindings, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.RepositoryID,
			&i.RuleKind,
			&i.RuleName,
			&i.Status,
			&i.Reason,
			&i.Remediation,
			&i.Evidence,
			&i.EvidenceVersion,
			&i.StatusSince,
			&i.LastEvaluatedAt,
			&i.PolicyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFinding = `-- name: UpsertFinding :exec
INSERT INTO findings (
    repository_id, rule_kind, rule_name, status, reason, remediation,
    evidence, evidence_version, status_since, last_evaluated_at, policy_version
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (repository_id, rule_kind, rule_name) DO UPDATE
SET status = excluded.status,
    reason = excluded.reason,
    remediation = excluded.remediation,
    evidence = excluded.evidence,
    evidence_version = excluded.evidence_version,
    status_since = excluded.status_since,
    last_evaluated_at = excluded.last_evaluated_at,
    policy_version = excluded.policy_version
`

type UpsertFindingParams struct {
	RepositoryID    int64
	RuleKind        string
	RuleName        string
	Status          string
	Reason          *string
	Remediation     string
	Evidence        json.RawMessage
	EvidenceVersion int16
	StatusSince     time.Time
	LastEvaluatedAt time.Time
	PolicyVersion   string
}

func (q *Queries) UpsertFinding(ctx context.Context, arg UpsertFindingParams) error {
	_, err := q.db.Exec(ctx, upsertFinding,
		arg.RepositoryID,
		arg.RuleKind,
		arg.RuleName,
		arg.Status,
		arg.Reason,
		arg.Remediation,
		arg.Evidence,
		arg.EvidenceVersion,
		arg.StatusSince,
		arg.LastEvaluatedAt,
		arg.PolicyVersion,
	)
	return err
}
