// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: installations.sql

package sqlcdb

import (
	"context"
	"time"
)

const markInstallationRemoved = `-- name: MarkInstallationRemoved :execrows
UPDATE installations SET removed_at = $2, updated_at = now() WHERE installation_id = $1
`

type MarkInstallationRemovedParams struct {
	InstallationID int64
	RemovedAt      *time.Time
}

func (q *Queries) MarkInstallationRemoved(ctx context.Context, arg MarkInstallationRemovedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markInstallationRemoved, arg.InstallationID, arg.RemovedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateInstallationRate = `-- name: UpdateInstallationRate :exec
UPDATE installations
SET rate_limit = $1,
    rate_remaining = $2,
    rate_reset_at = $3,
    rate_observed_at = $4,
    updated_at = now()
WHERE installation_id = $5
  AND (rate_observed_at IS NULL OR rate_observed_at < $4)
`

type UpdateInstallationRateParams struct {
	RateLimit      *int32
	RateRemaining  *int32
	RateResetAt    *time.Time
	RateObservedAt *time.Time
	InstallationID int64
}

// Keeps the newest observation: an older one never wins.
func (q *Queries) UpdateInstallationRate(ctx context.Context, arg UpdateInstallationRateParams) error {
	_, err := q.db.Exec(ctx, updateInstallationRate,
		arg.RateLimit,
		arg.RateRemaining,
		arg.RateResetAt,
		arg.RateObservedAt,
		arg.InstallationID,
	)
	return err
}

const upsertInstallation = `-- name: UpsertInstallation :exec
INSERT INTO installations (installation_id, provider, host, account_login, suspended_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (installation_id) DO UPDATE
SET account_login = excluded.account_login,
    suspended_at = excluded.suspended_at,
    removed_at = NULL,
    updated_at = now()
`

type UpsertInstallationParams struct {
	InstallationID int64
	Provider       string
	Host           string
	AccountLogin   string
	SuspendedAt    *time.Time
}

func (q *Queries) UpsertInstallation(ctx context.Context, arg UpsertInstallationParams) error {
	_, err := q.db.Exec(ctx, upsertInstallation,
		arg.InstallationID,
		arg.Provider,
		arg.Host,
		arg.AccountLogin,
		arg.SuspendedAt,
	)
	return err
}
