// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"encoding/json"
	"time"
)

type Check struct {
	ID            int64
	RepositoryID  int64
	CheckKey      string
	Trigger       string
	Outcome       string
	Error         *string
	PendingResult json.RawMessage
	PolicyVersion string
	StartedAt     time.Time
	FinishedAt    *time.Time
}

type ComplianceSnapshot struct {
	Org           string
	RuleKind      string
	RuleName      string
	SnapshotAt    time.Time
	Compliant     int32
	NonCompliant  int32
	NotApplicable int32
	Unknown       int32
}

type Finding struct {
	RepositoryID    int64
	RuleKind        string
	RuleName        string
	Status          string
	Reason          *string
	Remediation     string
	Evidence        json.RawMessage
	EvidenceVersion int16
	StatusSince     time.Time
	LastEvaluatedAt time.Time
	PolicyVersion   string
}

type FindingEvent struct {
	ID              int64
	RepositoryID    int64
	RuleKind        string
	RuleName        string
	CheckID         *int64
	FromStatus      *string
	ToStatus        *string
	FromReason      *string
	ToReason        *string
	FromRemediation *string
	ToRemediation   *string
	Evidence        json.RawMessage
	PolicyVersion   string
	OccurredAt      time.Time
}

type Installation struct {
	InstallationID int64
	Provider       string
	Host           string
	AccountLogin   string
	SuspendedAt    *time.Time
	RemovedAt      *time.Time
	RateLimit      *int32
	RateRemaining  *int32
	RateResetAt    *time.Time
	RateObservedAt *time.Time
	UpdatedAt      time.Time
}

type PolicyVersion struct {
	Version            string
	FirstSeenAt        time.Time
	RolloutCompletedAt *time.Time
	Summary            json.RawMessage
}

type Repository struct {
	ID               int64
	Provider         string
	Host             string
	Org              string
	Name             string
	ProviderRepoID   *int64
	InstallationID   int64
	Active           bool
	ParkReason       *string
	ParkedAt         *time.Time
	DiscoveredAt     time.Time
	NextDueAt        *time.Time
	LastCheckedAt    *time.Time
	LastCheckOutcome string
	LastError        *string
	PolicyVersion    string
	CatalogParseOk   *bool
}

type RepositoryEvent struct {
	ID           int64
	RepositoryID int64
	Kind         string
	Detail       json.RawMessage
	OccurredAt   time.Time
}

type ServiceRun struct {
	ID         int64
	Kind       string
	Outcome    string
	StartedAt  time.Time
	FinishedAt time.Time
	Detail     json.RawMessage
}
