// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policy.sql

package sqlcdb

import (
	"context"
	"encoding/json"
)

const completePolicyRollout = `-- name: CompletePolicyRollout :exec
UPDATE policy_versions SET rollout_completed_at = now()
WHERE version = $1 AND rollout_completed_at IS NULL
`

func (q *Queries) CompletePolicyRollout(ctx context.Context, version string) error {
	_, err := q.db.Exec(ctx, completePolicyRollout, version)
	return err
}

const insertPolicyVersion = `-- name: InsertPolicyVersion :execrows
INSERT INTO policy_versions (version, summary) VALUES ($1, $2)
ON CONFLICT (version) DO NOTHING
`

type InsertPolicyVersionParams struct {
	Version string
	Summary json.RawMessage
}

func (q *Queries) InsertPolicyVersion(ctx context.Context, arg InsertPolicyVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPolicyVersion, arg.Version, arg.Summary)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
