// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policy.sql

package sqlcdb

import (
	"context"
	"encoding/json"
)

const completePolicyRollout = `-- name: CompletePolicyRollout :exec
UPDATE policy_versions SET rollout_completed_at = now()
WHERE version = $1 AND rollout_completed_at IS NULL
`

func (q *Queries) CompletePolicyRollout(ctx context.Context, version string) error {
	_, err := q.db.Exec(ctx, completePolicyRollout, version)
	return err
}

const currentPolicyVersion = `-- name: CurrentPolicyVersion :one
SELECT version, first_seen_at, rollout_completed_at, summary
FROM policy_versions
ORDER BY first_seen_at DESC, version DESC
LIMIT 1
`

// The newest policy version. Global: the API's /policy is not org-scoped
// because the policy is one document for the whole fleet.
func (q *Queries) CurrentPolicyVersion(ctx context.Context) (PolicyVersion, error) {
	row := q.db.QueryRow(ctx, currentPolicyVersion)
	var i PolicyVersion
	err := row.Scan(
		&i.Version,
		&i.FirstSeenAt,
		&i.RolloutCompletedAt,
		&i.Summary,
	)
	return i, err
}

const insertPolicyVersion = `-- name: InsertPolicyVersion :execrows
INSERT INTO policy_versions (version, summary) VALUES ($1, $2)
ON CONFLICT (version) DO NOTHING
`

type InsertPolicyVersionParams struct {
	Version string
	Summary json.RawMessage
}

func (q *Queries) InsertPolicyVersion(ctx context.Context, arg InsertPolicyVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPolicyVersion, arg.Version, arg.Summary)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
