// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repositories.sql

package sqlcdb

import (
	"context"
	"time"
)

const getRepository = `-- name: GetRepository :one
SELECT id, provider, host, org, name, provider_repo_id, installation_id, active, park_reason, parked_at, discovered_at, next_due_at, last_checked_at, last_check_outcome, last_error, policy_version, catalog_parse_ok FROM repositories WHERE id = $1
`

func (q *Queries) GetRepository(ctx context.Context, id int64) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepository, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Host,
		&i.Org,
		&i.Name,
		&i.ProviderRepoID,
		&i.InstallationID,
		&i.Active,
		&i.ParkReason,
		&i.ParkedAt,
		&i.DiscoveredAt,
		&i.NextDueAt,
		&i.LastCheckedAt,
		&i.LastCheckOutcome,
		&i.LastError,
		&i.PolicyVersion,
		&i.CatalogParseOk,
	)
	return i, err
}

const insertRepository = `-- name: InsertRepository :one
INSERT INTO repositories (provider, host, org, name, provider_repo_id, installation_id, next_due_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT DO NOTHING
RETURNING id
`

type InsertRepositoryParams struct {
	Provider       string
	Host           string
	Org            string
	Name           string
	ProviderRepoID *int64
	InstallationID int64
	NextDueAt      *time.Time
}

func (q *Queries) InsertRepository(ctx context.Context, arg InsertRepositoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertRepository,
		arg.Provider,
		arg.Host,
		arg.Org,
		arg.Name,
		arg.ProviderRepoID,
		arg.InstallationID,
		arg.NextDueAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listActiveRepositories = `-- name: ListActiveRepositories :many
SELECT id, provider, host, org, name, provider_repo_id, installation_id, active, park_reason, parked_at, discovered_at, next_due_at, last_checked_at, last_check_outcome, last_error, policy_version, catalog_parse_ok FROM repositories
WHERE active AND id > $1
ORDER BY id
LIMIT $2
`

type ListActiveRepositoriesParams struct {
	AfterID   int64
	PageLimit int32
}

func (q *Queries) ListActiveRepositories(ctx context.Context, arg ListActiveRepositoriesParams) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listActiveRepositories, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Host,
			&i.Org,
			&i.Name,
			&i.ProviderRepoID,
			&i.InstallationID,
			&i.Active,
			&i.ParkReason,
			&i.ParkedAt,
			&i.DiscoveredAt,
			&i.NextDueAt,
			&i.LastCheckedAt,
			&i.LastCheckOutcome,
			&i.LastError,
			&i.PolicyVersion,
			&i.CatalogParseOk,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRepositoryByName = `-- name: LockRepositoryByName :one
SELECT id, provider, host, org, name, provider_repo_id, installation_id, active, park_reason, parked_at, discovered_at, next_due_at, last_checked_at, last_check_outcome, last_error, policy_version, catalog_parse_ok FROM repositories
WHERE provider = $1 AND host = $2 AND lower(org) = lower($3) AND lower(name) = lower($4)
FOR UPDATE
`

type LockRepositoryByNameParams struct {
	Provider string
	Host     string
	Org      string
	Name     string
}

func (q *Queries) LockRepositoryByName(ctx context.Context, arg LockRepositoryByNameParams) (Repository, error) {
	row := q.db.QueryRow(ctx, lockRepositoryByName,
		arg.Provider,
		arg.Host,
		arg.Org,
		arg.Name,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Host,
		&i.Org,
		&i.Name,
		&i.ProviderRepoID,
		&i.InstallationID,
		&i.Active,
		&i.ParkReason,
		&i.ParkedAt,
		&i.DiscoveredAt,
		&i.NextDueAt,
		&i.LastCheckedAt,
		&i.LastCheckOutcome,
		&i.LastError,
		&i.PolicyVersion,
		&i.CatalogParseOk,
	)
	return i, err
}

const parkInstallationRepositories = `-- name: ParkInstallationRepositories :many
UPDATE repositories
SET active = false, park_reason = 'installation_removed', parked_at = now()
WHERE installation_id = $1 AND active
RETURNING id
`

func (q *Queries) ParkInstallationRepositories(ctx context.Context, installationID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, parkInstallationRepositories, installationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const parkRepository = `-- name: ParkRepository :execrows
UPDATE repositories
SET active = false, park_reason = $1, parked_at = now()
WHERE id = $2
`

type ParkRepositoryParams struct {
	ParkReason *string
	ID         int64
}

func (q *Queries) ParkRepository(ctx context.Context, arg ParkRepositoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, parkRepository, arg.ParkReason, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reactivateRepository = `-- name: ReactivateRepository :exec
UPDATE repositories
SET active = true, park_reason = NULL, parked_at = NULL,
    installation_id = $1,
    provider_repo_id = coalesce(provider_repo_id, $2)
WHERE id = $3
`

type ReactivateRepositoryParams struct {
	InstallationID int64
	ProviderRepoID *int64
	ID             int64
}

func (q *Queries) ReactivateRepository(ctx context.Context, arg ReactivateRepositoryParams) error {
	_, err := q.db.Exec(ctx, reactivateRepository, arg.InstallationID, arg.ProviderRepoID, arg.ID)
	return err
}

const refreshRepositoryIdentity = `-- name: RefreshRepositoryIdentity :exec
UPDATE repositories
SET installation_id = $1,
    provider_repo_id = coalesce(provider_repo_id, $2)
WHERE id = $3
`

type RefreshRepositoryIdentityParams struct {
	InstallationID int64
	ProviderRepoID *int64
	ID             int64
}

func (q *Queries) RefreshRepositoryIdentity(ctx context.Context, arg RefreshRepositoryIdentityParams) error {
	_, err := q.db.Exec(ctx, refreshRepositoryIdentity, arg.InstallationID, arg.ProviderRepoID, arg.ID)
	return err
}

const updateRepositoryAfterCheck = `-- name: UpdateRepositoryAfterCheck :exec
UPDATE repositories
SET last_checked_at = $1,
    last_check_outcome = 'success',
    last_error = NULL,
    policy_version = $2,
    catalog_parse_ok = $3,
    provider_repo_id = coalesce($4, provider_repo_id),
    name = coalesce($5, name)
WHERE id = $6
`

type UpdateRepositoryAfterCheckParams struct {
	CheckedAt      *time.Time
	PolicyVersion  string
	CatalogParseOk *bool
	ProviderRepoID *int64
	Name           *string
	ID             int64
}

func (q *Queries) UpdateRepositoryAfterCheck(ctx context.Context, arg UpdateRepositoryAfterCheckParams) error {
	_, err := q.db.Exec(ctx, updateRepositoryAfterCheck,
		arg.CheckedAt,
		arg.PolicyVersion,
		arg.CatalogParseOk,
		arg.ProviderRepoID,
		arg.Name,
		arg.ID,
	)
	return err
}

const updateRepositoryAfterError = `-- name: UpdateRepositoryAfterError :exec
UPDATE repositories
SET last_checked_at = $1,
    last_check_outcome = 'error',
    last_error = $2
WHERE id = $3
`

type UpdateRepositoryAfterErrorParams struct {
	CheckedAt *time.Time
	LastError *string
	ID        int64
}

func (q *Queries) UpdateRepositoryAfterError(ctx context.Context, arg UpdateRepositoryAfterErrorParams) error {
	_, err := q.db.Exec(ctx, updateRepositoryAfterError, arg.CheckedAt, arg.LastError, arg.ID)
	return err
}
