// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service_runs.sql

package sqlcdb

import (
	"context"
	"encoding/json"
	"time"
)

const insertServiceRun = `-- name: InsertServiceRun :exec
INSERT INTO service_runs (kind, outcome, started_at, finished_at, detail)
VALUES ($1, $2, $3, $4, $5)
`

type InsertServiceRunParams struct {
	Kind       string
	Outcome    string
	StartedAt  time.Time
	FinishedAt time.Time
	Detail     json.RawMessage
}

func (q *Queries) InsertServiceRun(ctx context.Context, arg InsertServiceRunParams) error {
	_, err := q.db.Exec(ctx, insertServiceRun,
		arg.Kind,
		arg.Outcome,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Detail,
	)
	return err
}
