// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snapshots.sql

package sqlcdb

import (
	"context"
	"time"
)

const insertComplianceSnapshotRows = `-- name: InsertComplianceSnapshotRows :execrows
INSERT INTO compliance_snapshots (
    org, rule_kind, rule_name, snapshot_at, compliant, non_compliant, not_applicable, unknown
)
SELECT unnest($1::text[]), unnest($2::text[]), unnest($3::text[]),
       $4::timestamptz,
       unnest($5::int[]), unnest($6::int[]),
       unnest($7::int[]), unnest($8::int[])
ON CONFLICT DO NOTHING
`

type InsertComplianceSnapshotRowsParams struct {
	Orgs          []string
	RuleKinds     []string
	RuleNames     []string
	SnapshotAt    time.Time
	Compliant     []int32
	NonCompliant  []int32
	NotApplicable []int32
	Unknown       []int32
}

// Writes rows computed by ComplianceByRule, so a snapshot holds exactly
// the counts the report showed. Idempotent on the primary key, so a
// retried snapshot writes nothing new.
// Parallel unnest in the select list zips the equal-length arrays;
// sqlc cannot type the multi-argument FROM unnest(...) form.
func (q *Queries) InsertComplianceSnapshotRows(ctx context.Context, arg InsertComplianceSnapshotRowsParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertComplianceSnapshotRows,
		arg.Orgs,
		arg.RuleKinds,
		arg.RuleNames,
		arg.SnapshotAt,
		arg.Compliant,
		arg.NonCompliant,
		arg.NotApplicable,
		arg.Unknown,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
