// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: status.sql

package sqlcdb

import (
	"context"
	"time"
)

const statusChecks = `-- name: StatusChecks :one

SELECT (SELECT max(c.finished_at) FROM checks c WHERE c.outcome = 'success') AS last_success,
       (SELECT max(c.finished_at) FROM checks c WHERE c.trigger IN ('webhook', 'push')) AS last_webhook,
       (SELECT count(*) FROM checks c WHERE c.finished_at >= $1::timestamptz AND c.outcome = 'error')::int AS errors,
       (SELECT count(*) FROM checks c WHERE c.finished_at >= $1::timestamptz)::int AS finished,
       (SELECT count(*) FROM repositories r WHERE r.active)::int AS active_repositories
`

type StatusChecksRow struct {
	LastSuccess        interface{}
	LastWebhook        interface{}
	Errors             int32
	Finished           int32
	ActiveRepositories int32
}

// Status page inputs (DESIGN-0027 § Status page). Global and unscoped:
// the page is aggregate-only and never names an org. Read by the
// refresher every 30s, never per request.
func (q *Queries) StatusChecks(ctx context.Context, since time.Time) (StatusChecksRow, error) {
	row := q.db.QueryRow(ctx, statusChecks, since)
	var i StatusChecksRow
	err := row.Scan(
		&i.LastSuccess,
		&i.LastWebhook,
		&i.Errors,
		&i.Finished,
		&i.ActiveRepositories,
	)
	return i, err
}

const statusRates = `-- name: StatusRates :many
SELECT rate_limit::int AS rate_limit, rate_remaining::int AS rate_remaining, rate_reset_at::timestamptz AS rate_reset_at
FROM installations
WHERE removed_at IS NULL AND suspended_at IS NULL
  AND rate_observed_at IS NOT NULL AND rate_limit IS NOT NULL AND rate_remaining IS NOT NULL AND rate_reset_at IS NOT NULL
`

type StatusRatesRow struct {
	RateLimit     int32
	RateRemaining int32
	RateResetAt   time.Time
}

// Rate snapshots of live installations.
func (q *Queries) StatusRates(ctx context.Context) ([]StatusRatesRow, error) {
	rows, err := q.db.Query(ctx, statusRates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatusRatesRow
	for rows.Next() {
		var i StatusRatesRow
		if err := rows.Scan(&i.RateLimit, &i.RateRemaining, &i.RateResetAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statusServiceRuns = `-- name: StatusServiceRuns :many
SELECT kind, max(finished_at)::timestamptz AS last_success
FROM service_runs
WHERE outcome = 'success'
GROUP BY kind
`

type StatusServiceRunsRow struct {
	Kind        string
	LastSuccess time.Time
}

// The last successful run of each service.
func (q *Queries) StatusServiceRuns(ctx context.Context) ([]StatusServiceRunsRow, error) {
	rows, err := q.db.Query(ctx, statusServiceRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatusServiceRunsRow
	for rows.Next() {
		var i StatusServiceRunsRow
		if err := rows.Scan(&i.Kind, &i.LastSuccess); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
