// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/donaldgifford/repo-guardian/internal/github"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// AddLabelsToPR provides a mock function for the type MockClient
func (_mock *MockClient) AddLabelsToPR(ctx context.Context, owner string, repo string, prNumber int, labels []string) error {
	ret := _mock.Called(ctx, owner, repo, prNumber, labels)

	if len(ret) == 0 {
		panic("no return value specified for AddLabelsToPR")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, []string) error); ok {
		r0 = returnFunc(ctx, owner, repo, prNumber, labels)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_AddLabelsToPR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddLabelsToPR'
type MockClient_AddLabelsToPR_Call struct {
	*mock.Call
}

// AddLabelsToPR is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - prNumber int
//   - labels []string
func (_e *MockClient_Expecter) AddLabelsToPR(ctx any, owner any, repo any, prNumber any, labels any) *MockClient_AddLabelsToPR_Call {
	return &MockClient_AddLabelsToPR_Call{Call: _e.mock.On("AddLabelsToPR", ctx, owner, repo, prNumber, labels)}
}

func (_c *MockClient_AddLabelsToPR_Call) Run(run func(ctx context.Context, owner string, repo string, prNumber int, labels []string)) *MockClient_AddLabelsToPR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 []string
		if args[4] != nil {
			arg4 = args[4].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockClient_AddLabelsToPR_Call) Return(err error) *MockClient_AddLabelsToPR_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_AddLabelsToPR_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, prNumber int, labels []string) error) *MockClient_AddLabelsToPR_Call {
	_c.Call.Return(run)
	return _c
}

// ClosePullRequest provides a mock function for the type MockClient
func (_mock *MockClient) ClosePullRequest(ctx context.Context, owner string, repo string, number int) error {
	ret := _mock.Called(ctx, owner, repo, number)

	if len(ret) == 0 {
		panic("no return value specified for ClosePullRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) error); ok {
		r0 = returnFunc(ctx, owner, repo, number)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_ClosePullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClosePullRequest'
type MockClient_ClosePullRequest_Call struct {
	*mock.Call
}

// ClosePullRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - number int
func (_e *MockClient_Expecter) ClosePullRequest(ctx any, owner any, repo any, number any) *MockClient_ClosePullRequest_Call {
	return &MockClient_ClosePullRequest_Call{Call: _e.mock.On("ClosePullRequest", ctx, owner, repo, number)}
}

func (_c *MockClient_ClosePullRequest_Call) Run(run func(ctx context.Context, owner string, repo string, number int)) *MockClient_ClosePullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_ClosePullRequest_Call) Return(err error) *MockClient_ClosePullRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_ClosePullRequest_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, number int) error) *MockClient_ClosePullRequest_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBranch provides a mock function for the type MockClient
func (_mock *MockClient) CreateBranch(ctx context.Context, owner string, repo string, branch string, baseSHA string) error {
	ret := _mock.Called(ctx, owner, repo, branch, baseSHA)

	if len(ret) == 0 {
		panic("no return value specified for CreateBranch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, owner, repo, branch, baseSHA)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_CreateBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBranch'
type MockClient_CreateBranch_Call struct {
	*mock.Call
}

// CreateBranch is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - branch string
//   - baseSHA string
func (_e *MockClient_Expecter) CreateBranch(ctx any, owner any, repo any, branch any, baseSHA any) *MockClient_CreateBranch_Call {
	return &MockClient_CreateBranch_Call{Call: _e.mock.On("CreateBranch", ctx, owner, repo, branch, baseSHA)}
}

func (_c *MockClient_CreateBranch_Call) Run(run func(ctx context.Context, owner string, repo string, branch string, baseSHA string)) *MockClient_CreateBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockClient_CreateBranch_Call) Return(err error) *MockClient_CreateBranch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_CreateBranch_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, branch string, baseSHA string) error) *MockClient_CreateBranch_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInstallationClient provides a mock function for the type MockClient
func (_mock *MockClient) CreateInstallationClient(ctx context.Context, installationID int64) (github.Client, error) {
	ret := _mock.Called(ctx, installationID)

	if len(ret) == 0 {
		panic("no return value specified for CreateInstallationClient")
	}

	var r0 github.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (github.Client, error)); ok {
		return returnFunc(ctx, installationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) github.Client); ok {
		r0 = returnFunc(ctx, installationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(github.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, installationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_CreateInstallationClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInstallationClient'
type MockClient_CreateInstallationClient_Call struct {
	*mock.Call
}

// CreateInstallationClient is a helper method to define mock.On call
//   - ctx context.Context
//   - installationID int64
func (_e *MockClient_Expecter) CreateInstallationClient(ctx any, installationID any) *MockClient_CreateInstallationClient_Call {
	return &MockClient_CreateInstallationClient_Call{Call: _e.mock.On("CreateInstallationClient", ctx, installationID)}
}

func (_c *MockClient_CreateInstallationClient_Call) Run(run func(ctx context.Context, installationID int64)) *MockClient_CreateInstallationClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_CreateInstallationClient_Call) Return(client github.Client, err error) *MockClient_CreateInstallationClient_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockClient_CreateInstallationClient_Call) RunAndReturn(run func(ctx context.Context, installationID int64) (github.Client, error)) *MockClient_CreateInstallationClient_Call {
	_c.Call.Return(run)
	return _c
}

// CreateLabel provides a mock function for the type MockClient
func (_mock *MockClient) CreateLabel(ctx context.Context, owner string, repo string, label *github.Label) error {
	ret := _mock.Called(ctx, owner, repo, label)

	if len(ret) == 0 {
		panic("no return value specified for CreateLabel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *github.Label) error); ok {
		r0 = returnFunc(ctx, owner, repo, label)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_CreateLabel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLabel'
type MockClient_CreateLabel_Call struct {
	*mock.Call
}

// CreateLabel is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - label *github.Label
func (_e *MockClient_Expecter) CreateLabel(ctx any, owner any, repo any, label any) *MockClient_CreateLabel_Call {
	return &MockClient_CreateLabel_Call{Call: _e.mock.On("CreateLabel", ctx, owner, repo, label)}
}

func (_c *MockClient_CreateLabel_Call) Run(run func(ctx context.Context, owner string, repo string, label *github.Label)) *MockClient_CreateLabel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *github.Label
		if args[3] != nil {
			arg3 = args[3].(*github.Label)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_CreateLabel_Call) Return(err error) *MockClient_CreateLabel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_CreateLabel_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, label *github.Label) error) *MockClient_CreateLabel_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrUpdateFile provides a mock function for the type MockClient
func (_mock *MockClient) CreateOrUpdateFile(ctx context.Context, owner string, repo string, branch string, path string, content string, message string) error {
	ret := _mock.Called(ctx, owner, repo, branch, path, content, message)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdateFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, owner, repo, branch, path, content, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_CreateOrUpdateFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdateFile'
type MockClient_CreateOrUpdateFile_Call struct {
	*mock.Call
}

// CreateOrUpdateFile is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - branch string
//   - path string
//   - content string
//   - message string
func (_e *MockClient_Expecter) CreateOrUpdateFile(ctx any, owner any, repo any, branch any, path any, content any, message any) *MockClient_CreateOrUpdateFile_Call {
	return &MockClient_CreateOrUpdateFile_Call{Call: _e.mock.On("CreateOrUpdateFile", ctx, owner, repo, branch, path, content, message)}
}

func (_c *MockClient_CreateOrUpdateFile_Call) Run(run func(ctx context.Context, owner string, repo string, branch string, path string, content string, message string)) *MockClient_CreateOrUpdateFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockClient_CreateOrUpdateFile_Call) Return(err error) *MockClient_CreateOrUpdateFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_CreateOrUpdateFile_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, branch string, path string, content string, message string) error) *MockClient_CreateOrUpdateFile_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePullRequest provides a mock function for the type MockClient
func (_mock *MockClient) CreatePullRequest(ctx context.Context, owner string, repo string, title string, body string, head string, base string) (*github.PullRequest, error) {
	ret := _mock.Called(ctx, owner, repo, title, body, head, base)

	if len(ret) == 0 {
		panic("no return value specified for CreatePullRequest")
	}

	var r0 *github.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string) (*github.PullRequest, error)); ok {
		return returnFunc(ctx, owner, repo, title, body, head, base)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string) *github.PullRequest); ok {
		r0 = returnFunc(ctx, owner, repo, title, body, head, base)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, owner, repo, title, body, head, base)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_CreatePullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePullRequest'
type MockClient_CreatePullRequest_Call struct {
	*mock.Call
}

// CreatePullRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - title string
//   - body string
//   - head string
//   - base string
func (_e *MockClient_Expecter) CreatePullRequest(ctx any, owner any, repo any, title any, body any, head any, base any) *MockClient_CreatePullRequest_Call {
	return &MockClient_CreatePullRequest_Call{Call: _e.mock.On("CreatePullRequest", ctx, owner, repo, title, body, head, base)}
}

func (_c *MockClient_CreatePullRequest_Call) Run(run func(ctx context.Context, owner string, repo string, title string, body string, head string, base string)) *MockClient_CreatePullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockClient_CreatePullRequest_Call) Return(pullRequest *github.PullRequest, err error) *MockClient_CreatePullRequest_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockClient_CreatePullRequest_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, title string, body string, head string, base string) (*github.PullRequest, error)) *MockClient_CreatePullRequest_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRepositoryRuleset provides a mock function for the type MockClient
func (_mock *MockClient) CreateRepositoryRuleset(ctx context.Context, owner string, repo string, ruleset *github.Ruleset) (*github.Ruleset, error) {
	ret := _mock.Called(ctx, owner, repo, ruleset)

	if len(ret) == 0 {
		panic("no return value specified for CreateRepositoryRuleset")
	}

	var r0 *github.Ruleset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *github.Ruleset) (*github.Ruleset, error)); ok {
		return returnFunc(ctx, owner, repo, ruleset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *github.Ruleset) *github.Ruleset); ok {
		r0 = returnFunc(ctx, owner, repo, ruleset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Ruleset)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *github.Ruleset) error); ok {
		r1 = returnFunc(ctx, owner, repo, ruleset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_CreateRepositoryRuleset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRepositoryRuleset'
type MockClient_CreateRepositoryRuleset_Call struct {
	*mock.Call
}

// CreateRepositoryRuleset is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - ruleset *github.Ruleset
func (_e *MockClient_Expecter) CreateRepositoryRuleset(ctx any, owner any, repo any, ruleset any) *MockClient_CreateRepositoryRuleset_Call {
	return &MockClient_CreateRepositoryRuleset_Call{Call: _e.mock.On("CreateRepositoryRuleset", ctx, owner, repo, ruleset)}
}

func (_c *MockClient_CreateRepositoryRuleset_Call) Run(run func(ctx context.Context, owner string, repo string, ruleset *github.Ruleset)) *MockClient_CreateRepositoryRuleset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *github.Ruleset
		if args[3] != nil {
			arg3 = args[3].(*github.Ruleset)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_CreateRepositoryRuleset_Call) Return(ruleset1 *github.Ruleset, err error) *MockClient_CreateRepositoryRuleset_Call {
	_c.Call.Return(ruleset1, err)
	return _c
}

func (_c *MockClient_CreateRepositoryRuleset_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, ruleset *github.Ruleset) (*github.Ruleset, error)) *MockClient_CreateRepositoryRuleset_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBranch provides a mock function for the type MockClient
func (_mock *MockClient) DeleteBranch(ctx context.Context, owner string, repo string, branch string) error {
	ret := _mock.Called(ctx, owner, repo, branch)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBranch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, owner, repo, branch)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_DeleteBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBranch'
type MockClient_DeleteBranch_Call struct {
	*mock.Call
}

// DeleteBranch is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - branch string
func (_e *MockClient_Expecter) DeleteBranch(ctx any, owner any, repo any, branch any) *MockClient_DeleteBranch_Call {
	return &MockClient_DeleteBranch_Call{Call: _e.mock.On("DeleteBranch", ctx, owner, repo, branch)}
}

func (_c *MockClient_DeleteBranch_Call) Run(run func(ctx context.Context, owner string, repo string, branch string)) *MockClient_DeleteBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_DeleteBranch_Call) Return(err error) *MockClient_DeleteBranch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_DeleteBranch_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, branch string) error) *MockClient_DeleteBranch_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFile provides a mock function for the type MockClient
func (_mock *MockClient) DeleteFile(ctx context.Context, owner string, repo string, branch string, path string, sha string, message string) error {
	ret := _mock.Called(ctx, owner, repo, branch, path, sha, message)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, owner, repo, branch, path, sha, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'
type MockClient_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - branch string
//   - path string
//   - sha string
//   - message string
func (_e *MockClient_Expecter) DeleteFile(ctx any, owner any, repo any, branch any, path any, sha any, message any) *MockClient_DeleteFile_Call {
	return &MockClient_DeleteFile_Call{Call: _e.mock.On("DeleteFile", ctx, owner, repo, branch, path, sha, message)}
}

func (_c *MockClient_DeleteFile_Call) Run(run func(ctx context.Context, owner string, repo string, branch string, path string, sha string, message string)) *MockClient_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockClient_DeleteFile_Call) Return(err error) *MockClient_DeleteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_DeleteFile_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, branch string, path string, sha string, message string) error) *MockClient_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLabel provides a mock function for the type MockClient
func (_mock *MockClient) DeleteLabel(ctx context.Context, owner string, repo string, name string) error {
	ret := _mock.Called(ctx, owner, repo, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLabel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, owner, repo, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_DeleteLabel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLabel'
type MockClient_DeleteLabel_Call struct {
	*mock.Call
}

// DeleteLabel is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - name string
func (_e *MockClient_Expecter) DeleteLabel(ctx any, owner any, repo any, name any) *MockClient_DeleteLabel_Call {
	return &MockClient_DeleteLabel_Call{Call: _e.mock.On("DeleteLabel", ctx, owner, repo, name)}
}

func (_c *MockClient_DeleteLabel_Call) Run(run func(ctx context.Context, owner string, repo string, name string)) *MockClient_DeleteLabel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_DeleteLabel_Call) Return(err error) *MockClient_DeleteLabel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_DeleteLabel_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, name string) error) *MockClient_DeleteLabel_Call {
	_c.Call.Return(run)
	return _c
}

// DisableVulnerabilityAlerts provides a mock function for the type MockClient
func (_mock *MockClient) DisableVulnerabilityAlerts(ctx context.Context, owner string, repo string) error {
	ret := _mock.Called(ctx, owner, repo)

	if len(ret) == 0 {
		panic("no return value specified for DisableVulnerabilityAlerts")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, owner, repo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_DisableVulnerabilityAlerts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableVulnerabilityAlerts'
type MockClient_DisableVulnerabilityAlerts_Call struct {
	*mock.Call
}

// DisableVulnerabilityAlerts is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
func (_e *MockClient_Expecter) DisableVulnerabilityAlerts(ctx any, owner any, repo any) *MockClient_DisableVulnerabilityAlerts_Call {
	return &MockClient_DisableVulnerabilityAlerts_Call{Call: _e.mock.On("DisableVulnerabilityAlerts", ctx, owner, repo)}
}

func (_c *MockClient_DisableVulnerabilityAlerts_Call) Run(run func(ctx context.Context, owner string, repo string)) *MockClient_DisableVulnerabilityAlerts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_DisableVulnerabilityAlerts_Call) Return(err error) *MockClient_DisableVulnerabilityAlerts_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_DisableVulnerabilityAlerts_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string) error) *MockClient_DisableVulnerabilityAlerts_Call {
	_c.Call.Return(run)
	return _c
}

// EnableVulnerabilityAlerts provides a mock function for the type MockClient
func (_mock *MockClient) EnableVulnerabilityAlerts(ctx context.Context, owner string, repo string) error {
	ret := _mock.Called(ctx, owner, repo)

	if len(ret) == 0 {
		panic("no return value specified for EnableVulnerabilityAlerts")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, owner, repo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_EnableVulnerabilityAlerts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableVulnerabilityAlerts'
type MockClient_EnableVulnerabilityAlerts_Call struct {
	*mock.Call
}

// EnableVulnerabilityAlerts is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
func (_e *MockClient_Expecter) EnableVulnerabilityAlerts(ctx any, owner any, repo any) *MockClient_EnableVulnerabilityAlerts_Call {
	return &MockClient_EnableVulnerabilityAlerts_Call{Call: _e.mock.On("EnableVulnerabilityAlerts", ctx, owner, repo)}
}

func (_c *MockClient_EnableVulnerabilityAlerts_Call) Run(run func(ctx context.Context, owner string, repo string)) *MockClient_EnableVulnerabilityAlerts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_EnableVulnerabilityAlerts_Call) Return(err error) *MockClient_EnableVulnerabilityAlerts_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_EnableVulnerabilityAlerts_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string) error) *MockClient_EnableVulnerabilityAlerts_Call {
	_c.Call.Return(run)
	return _c
}

// GetBranchSHA provides a mock function for the type MockClient
func (_mock *MockClient) GetBranchSHA(ctx context.Context, owner string, repo string, branch string) (string, error) {
	ret := _mock.Called(ctx, owner, repo, branch)

	if len(ret) == 0 {
		panic("no return value specified for GetBranchSHA")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return returnFunc(ctx, owner, repo, branch)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = returnFunc(ctx, owner, repo, branch)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, owner, repo, branch)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetBranchSHA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBranchSHA'
type MockClient_GetBranchSHA_Call struct {
	*mock.Call
}

// GetBranchSHA is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - branch string
func (_e *MockClient_Expecter) GetBranchSHA(ctx any, owner any, repo any, branch any) *MockClient_GetBranchSHA_Call {
	return &MockClient_GetBranchSHA_Call{Call: _e.mock.On("GetBranchSHA", ctx, owner, repo, branch)}
}

func (_c *MockClient_GetBranchSHA_Call) Run(run func(ctx context.Context, owner string, repo string, branch string)) *MockClient_GetBranchSHA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_GetBranchSHA_Call) Return(s string, err error) *MockClient_GetBranchSHA_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockClient_GetBranchSHA_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, branch string) (string, error)) *MockClient_GetBranchSHA_Call {
	_c.Call.Return(run)
	return _c
}

// GetContents provides a mock function for the type MockClient
func (_mock *MockClient) GetContents(ctx context.Context, owner string, repo string, path string) (bool, error) {
	ret := _mock.Called(ctx, owner, repo, path)

	if len(ret) == 0 {
		panic("no return value specified for GetContents")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (bool, error)); ok {
		return returnFunc(ctx, owner, repo, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) bool); ok {
		r0 = returnFunc(ctx, owner, repo, path)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, owner, repo, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetContents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContents'
type MockClient_GetContents_Call struct {
	*mock.Call
}

// GetContents is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - path string
func (_e *MockClient_Expecter) GetContents(ctx any, owner any, repo any, path any) *MockClient_GetContents_Call {
	return &MockClient_GetContents_Call{Call: _e.mock.On("GetContents", ctx, owner, repo, path)}
}

func (_c *MockClient_GetContents_Call) Run(run func(ctx context.Context, owner string, repo string, path string)) *MockClient_GetContents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_GetContents_Call) Return(b bool, err error) *MockClient_GetContents_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockClient_GetContents_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, path string) (bool, error)) *MockClient_GetContents_Call {
	_c.Call.Return(run)
	return _c
}

// GetContentsOnBranch provides a mock function for the type MockClient
func (_mock *MockClient) GetContentsOnBranch(ctx context.Context, owner string, repo string, path string, branch string) (string, bool, error) {
	ret := _mock.Called(ctx, owner, repo, path, branch)

	if len(ret) == 0 {
		panic("no return value specified for GetContentsOnBranch")
	}

	var r0 string
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (string, bool, error)); ok {
		return returnFunc(ctx, owner, repo, path, branch)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) string); ok {
		r0 = returnFunc(ctx, owner, repo, path, branch)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) bool); ok {
		r1 = returnFunc(ctx, owner, repo, path, branch)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string, string) error); ok {
		r2 = returnFunc(ctx, owner, repo, path, branch)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockClient_GetContentsOnBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContentsOnBranch'
type MockClient_GetContentsOnBranch_Call struct {
	*mock.Call
}

// GetContentsOnBranch is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - path string
//   - branch string
func (_e *MockClient_Expecter) GetContentsOnBranch(ctx any, owner any, repo any, path any, branch any) *MockClient_GetContentsOnBranch_Call {
	return &MockClient_GetContentsOnBranch_Call{Call: _e.mock.On("GetContentsOnBranch", ctx, owner, repo, path, branch)}
}

func (_c *MockClient_GetContentsOnBranch_Call) Run(run func(ctx context.Context, owner string, repo string, path string, branch string)) *MockClient_GetContentsOnBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockClient_GetContentsOnBranch_Call) Return(sha string, exists bool, err error) *MockClient_GetContentsOnBranch_Call {
	_c.Call.Return(sha, exists, err)
	return _c
}

func (_c *MockClient_GetContentsOnBranch_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, path string, branch string) (string, bool, error)) *MockClient_GetContentsOnBranch_Call {
	_c.Call.Return(run)
	return _c
}

// GetCustomPropertyValues provides a mock function for the type MockClient
func (_mock *MockClient) GetCustomPropertyValues(ctx context.Context, owner string, repo string) ([]*github.CustomPropertyValue, error) {
	ret := _mock.Called(ctx, owner, repo)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomPropertyValues")
	}

	var r0 []*github.CustomPropertyValue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]*github.CustomPropertyValue, error)); ok {
		return returnFunc(ctx, owner, repo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []*github.CustomPropertyValue); ok {
		r0 = returnFunc(ctx, owner, repo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*github.CustomPropertyValue)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, owner, repo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetCustomPropertyValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomPropertyValues'
type MockClient_GetCustomPropertyValues_Call struct {
	*mock.Call
}

// GetCustomPropertyValues is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
func (_e *MockClient_Expecter) GetCustomPropertyValues(ctx any, owner any, repo any) *MockClient_GetCustomPropertyValues_Call {
	return &MockClient_GetCustomPropertyValues_Call{Call: _e.mock.On("GetCustomPropertyValues", ctx, owner, repo)}
}

func (_c *MockClient_GetCustomPropertyValues_Call) Run(run func(ctx context.Context, owner string, repo string)) *MockClient_GetCustomPropertyValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_GetCustomPropertyValues_Call) Return(customPropertyValues []*github.CustomPropertyValue, err error) *MockClient_GetCustomPropertyValues_Call {
	_c.Call.Return(customPropertyValues, err)
	return _c
}

func (_c *MockClient_GetCustomPropertyValues_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string) ([]*github.CustomPropertyValue, error)) *MockClient_GetCustomPropertyValues_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileContent provides a mock function for the type MockClient
func (_mock *MockClient) GetFileContent(ctx context.Context, owner string, repo string, path string) (string, error) {
	ret := _mock.Called(ctx, owner, repo, path)

	if len(ret) == 0 {
		panic("no return value specified for GetFileContent")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return returnFunc(ctx, owner, repo, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = returnFunc(ctx, owner, repo, path)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, owner, repo, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetFileContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileContent'
type MockClient_GetFileContent_Call struct {
	*mock.Call
}

// GetFileContent is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - path string
func (_e *MockClient_Expecter) GetFileContent(ctx any, owner any, repo any, path any) *MockClient_GetFileContent_Call {
	return &MockClient_GetFileContent_Call{Call: _e.mock.On("GetFileContent", ctx, owner, repo, path)}
}

func (_c *MockClient_GetFileContent_Call) Run(run func(ctx context.Context, owner string, repo string, path string)) *MockClient_GetFileContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_GetFileContent_Call) Return(s string, err error) *MockClient_GetFileContent_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockClient_GetFileContent_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, path string) (string, error)) *MockClient_GetFileContent_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrgPropertySchema provides a mock function for the type MockClient
func (_mock *MockClient) GetOrgPropertySchema(ctx context.Context, org string) ([]string, error) {
	ret := _mock.Called(ctx, org)

	if len(ret) == 0 {
		panic("no return value specified for GetOrgPropertySchema")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, org)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, org)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, org)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetOrgPropertySchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrgPropertySchema'
type MockClient_GetOrgPropertySchema_Call struct {
	*mock.Call
}

// GetOrgPropertySchema is a helper method to define mock.On call
//   - ctx context.Context
//   - org string
func (_e *MockClient_Expecter) GetOrgPropertySchema(ctx any, org any) *MockClient_GetOrgPropertySchema_Call {
	return &MockClient_GetOrgPropertySchema_Call{Call: _e.mock.On("GetOrgPropertySchema", ctx, org)}
}

func (_c *MockClient_GetOrgPropertySchema_Call) Run(run func(ctx context.Context, org string)) *MockClient_GetOrgPropertySchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetOrgPropertySchema_Call) Return(strings []string, err error) *MockClient_GetOrgPropertySchema_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockClient_GetOrgPropertySchema_Call) RunAndReturn(run func(ctx context.Context, org string) ([]string, error)) *MockClient_GetOrgPropertySchema_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepoSettings provides a mock function for the type MockClient
func (_mock *MockClient) GetRepoSettings(ctx context.Context, owner string, repo string) (*github.RepoSettings, error) {
	ret := _mock.Called(ctx, owner, repo)

	if len(ret) == 0 {
		panic("no return value specified for GetRepoSettings")
	}

	var r0 *github.RepoSettings
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*github.RepoSettings, error)); ok {
		return returnFunc(ctx, owner, repo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *github.RepoSettings); ok {
		r0 = returnFunc(ctx, owner, repo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.RepoSettings)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, owner, repo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetRepoSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepoSettings'
type MockClient_GetRepoSettings_Call struct {
	*mock.Call
}

// GetRepoSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
func (_e *MockClient_Expecter) GetRepoSettings(ctx any, owner any, repo any) *MockClient_GetRepoSettings_Call {
	return &MockClient_GetRepoSettings_Call{Call: _e.mock.On("GetRepoSettings", ctx, owner, repo)}
}

func (_c *MockClient_GetRepoSettings_Call) Run(run func(ctx context.Context, owner string, repo string)) *MockClient_GetRepoSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_GetRepoSettings_Call) Return(repoSettings *github.RepoSettings, err error) *MockClient_GetRepoSettings_Call {
	_c.Call.Return(repoSettings, err)
	return _c
}

func (_c *MockClient_GetRepoSettings_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string) (*github.RepoSettings, error)) *MockClient_GetRepoSettings_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepository provides a mock function for the type MockClient
func (_mock *MockClient) GetRepository(ctx context.Context, owner string, repo string) (*github.Repository, error) {
	ret := _mock.Called(ctx, owner, repo)

	if len(ret) == 0 {
		panic("no return value specified for GetRepository")
	}

	var r0 *github.Repository
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*github.Repository, error)); ok {
		return returnFunc(ctx, owner, repo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *github.Repository); ok {
		r0 = returnFunc(ctx, owner, repo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Repository)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, owner, repo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepository'
type MockClient_GetRepository_Call struct {
	*mock.Call
}

// GetRepository is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
func (_e *MockClient_Expecter) GetRepository(ctx any, owner any, repo any) *MockClient_GetRepository_Call {
	return &MockClient_GetRepository_Call{Call: _e.mock.On("GetRepository", ctx, owner, repo)}
}

func (_c *MockClient_GetRepository_Call) Run(run func(ctx context.Context, owner string, repo string)) *MockClient_GetRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_GetRepository_Call) Return(repository *github.Repository, err error) *MockClient_GetRepository_Call {
	_c.Call.Return(repository, err)
	return _c
}

func (_c *MockClient_GetRepository_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string) (*github.Repository, error)) *MockClient_GetRepository_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepositoryRuleset provides a mock function for the type MockClient
func (_mock *MockClient) GetRepositoryRuleset(ctx context.Context, owner string, repo string, rulesetID int64) (*github.Ruleset, error) {
	ret := _mock.Called(ctx, owner, repo, rulesetID)

	if len(ret) == 0 {
		panic("no return value specified for GetRepositoryRuleset")
	}

	var r0 *github.Ruleset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) (*github.Ruleset, error)); ok {
		return returnFunc(ctx, owner, repo, rulesetID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) *github.Ruleset); ok {
		r0 = returnFunc(ctx, owner, repo, rulesetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Ruleset)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int64) error); ok {
		r1 = returnFunc(ctx, owner, repo, rulesetID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetRepositoryRuleset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepositoryRuleset'
type MockClient_GetRepositoryRuleset_Call struct {
	*mock.Call
}

// GetRepositoryRuleset is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - rulesetID int64
func (_e *MockClient_Expecter) GetRepositoryRuleset(ctx any, owner any, repo any, rulesetID any) *MockClient_GetRepositoryRuleset_Call {
	return &MockClient_GetRepositoryRuleset_Call{Call: _e.mock.On("GetRepositoryRuleset", ctx, owner, repo, rulesetID)}
}

func (_c *MockClient_GetRepositoryRuleset_Call) Run(run func(ctx context.Context, owner string, repo string, rulesetID int64)) *MockClient_GetRepositoryRuleset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_GetRepositoryRuleset_Call) Return(ruleset *github.Ruleset, err error) *MockClient_GetRepositoryRuleset_Call {
	_c.Call.Return(ruleset, err)
	return _c
}

func (_c *MockClient_GetRepositoryRuleset_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, rulesetID int64) (*github.Ruleset, error)) *MockClient_GetRepositoryRuleset_Call {
	_c.Call.Return(run)
	return _c
}

// GetVulnerabilityAlertsEnabled provides a mock function for the type MockClient
func (_mock *MockClient) GetVulnerabilityAlertsEnabled(ctx context.Context, owner string, repo string) (bool, error) {
	ret := _mock.Called(ctx, owner, repo)

	if len(ret) == 0 {
		panic("no return value specified for GetVulnerabilityAlertsEnabled")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, owner, repo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, owner, repo)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, owner, repo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetVulnerabilityAlertsEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVulnerabilityAlertsEnabled'
type MockClient_GetVulnerabilityAlertsEnabled_Call struct {
	*mock.Call
}

// GetVulnerabilityAlertsEnabled is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
func (_e *MockClient_Expecter) GetVulnerabilityAlertsEnabled(ctx any, owner any, repo any) *MockClient_GetVulnerabilityAlertsEnabled_Call {
	return &MockClient_GetVulnerabilityAlertsEnabled_Call{Call: _e.mock.On("GetVulnerabilityAlertsEnabled", ctx, owner, repo)}
}

func (_c *MockClient_GetVulnerabilityAlertsEnabled_Call) Run(run func(ctx context.Context, owner string, repo string)) *MockClient_GetVulnerabilityAlertsEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_GetVulnerabilityAlertsEnabled_Call) Return(b bool, err error) *MockClient_GetVulnerabilityAlertsEnabled_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockClient_GetVulnerabilityAlertsEnabled_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string) (bool, error)) *MockClient_GetVulnerabilityAlertsEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// ListInstallationRepos provides a mock function for the type MockClient
func (_mock *MockClient) ListInstallationRepos(ctx context.Context, installationID int64) ([]*github.Repository, error) {
	ret := _mock.Called(ctx, installationID)

	if len(ret) == 0 {
		panic("no return value specified for ListInstallationRepos")
	}

	var r0 []*github.Repository
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]*github.Repository, error)); ok {
		return returnFunc(ctx, installationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []*github.Repository); ok {
		r0 = returnFunc(ctx, installationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*github.Repository)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, installationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListInstallationRepos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInstallationRepos'
type MockClient_ListInstallationRepos_Call struct {
	*mock.Call
}

// ListInstallationRepos is a helper method to define mock.On call
//   - ctx context.Context
//   - installationID int64
func (_e *MockClient_Expecter) ListInstallationRepos(ctx any, installationID any) *MockClient_ListInstallationRepos_Call {
	return &MockClient_ListInstallationRepos_Call{Call: _e.mock.On("ListInstallationRepos", ctx, installationID)}
}

func (_c *MockClient_ListInstallationRepos_Call) Run(run func(ctx context.Context, installationID int64)) *MockClient_ListInstallationRepos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_ListInstallationRepos_Call) Return(repositorys []*github.Repository, err error) *MockClient_ListInstallationRepos_Call {
	_c.Call.Return(repositorys, err)
	return _c
}

func (_c *MockClient_ListInstallationRepos_Call) RunAndReturn(run func(ctx context.Context, installationID int64) ([]*github.Repository, error)) *MockClient_ListInstallationRepos_Call {
	_c.Call.Return(run)
	return _c
}

// ListInstallations provides a mock function for the type MockClient
func (_mock *MockClient) ListInstallations(ctx context.Context) ([]*github.Installation, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListInstallations")
	}

	var r0 []*github.Installation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*github.Installation, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*github.Installation); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*github.Installation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListInstallations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInstallations'
type MockClient_ListInstallations_Call struct {
	*mock.Call
}

// ListInstallations is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) ListInstallations(ctx any) *MockClient_ListInstallations_Call {
	return &MockClient_ListInstallations_Call{Call: _e.mock.On("ListInstallations", ctx)}
}

func (_c *MockClient_ListInstallations_Call) Run(run func(ctx context.Context)) *MockClient_ListInstallations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_ListInstallations_Call) Return(installations []*github.Installation, err error) *MockClient_ListInstallations_Call {
	_c.Call.Return(installations, err)
	return _c
}

func (_c *MockClient_ListInstallations_Call) RunAndReturn(run func(ctx context.Context) ([]*github.Installation, error)) *MockClient_ListInstallations_Call {
	_c.Call.Return(run)
	return _c
}

// ListLabels provides a mock function for the type MockClient
func (_mock *MockClient) ListLabels(ctx context.Context, owner string, repo string) ([]*github.Label, error) {
	ret := _mock.Called(ctx, owner, repo)

	if len(ret) == 0 {
		panic("no return value specified for ListLabels")
	}

	var r0 []*github.Label
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]*github.Label, error)); ok {
		return returnFunc(ctx, owner, repo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []*github.Label); ok {
		r0 = returnFunc(ctx, owner, repo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*github.Label)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, owner, repo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListLabels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListLabels'
type MockClient_ListLabels_Call struct {
	*mock.Call
}

// ListLabels is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
func (_e *MockClient_Expecter) ListLabels(ctx any, owner any, repo any) *MockClient_ListLabels_Call {
	return &MockClient_ListLabels_Call{Call: _e.mock.On("ListLabels", ctx, owner, repo)}
}

func (_c *MockClient_ListLabels_Call) Run(run func(ctx context.Context, owner string, repo string)) *MockClient_ListLabels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_ListLabels_Call) Return(labels []*github.Label, err error) *MockClient_ListLabels_Call {
	_c.Call.Return(labels, err)
	return _c
}

func (_c *MockClient_ListLabels_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string) ([]*github.Label, error)) *MockClient_ListLabels_Call {
	_c.Call.Return(run)
	return _c
}

// ListOpenPullRequests provides a mock function for the type MockClient
func (_mock *MockClient) ListOpenPullRequests(ctx context.Context, owner string, repo string) ([]*github.PullRequest, error) {
	ret := _mock.Called(ctx, owner, repo)

	if len(ret) == 0 {
		panic("no return value specified for ListOpenPullRequests")
	}

	var r0 []*github.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]*github.PullRequest, error)); ok {
		return returnFunc(ctx, owner, repo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []*github.PullRequest); ok {
		r0 = returnFunc(ctx, owner, repo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*github.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, owner, repo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListOpenPullRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOpenPullRequests'
type MockClient_ListOpenPullRequests_Call struct {
	*mock.Call
}

// ListOpenPullRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
func (_e *MockClient_Expecter) ListOpenPullRequests(ctx any, owner any, repo any) *MockClient_ListOpenPullRequests_Call {
	return &MockClient_ListOpenPullRequests_Call{Call: _e.mock.On("ListOpenPullRequests", ctx, owner, repo)}
}

func (_c *MockClient_ListOpenPullRequests_Call) Run(run func(ctx context.Context, owner string, repo string)) *MockClient_ListOpenPullRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_ListOpenPullRequests_Call) Return(pullRequests []*github.PullRequest, err error) *MockClient_ListOpenPullRequests_Call {
	_c.Call.Return(pullRequests, err)
	return _c
}

func (_c *MockClient_ListOpenPullRequests_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string) ([]*github.PullRequest, error)) *MockClient_ListOpenPullRequests_Call {
	_c.Call.Return(run)
	return _c
}

// ListPRComments provides a mock function for the type MockClient
func (_mock *MockClient) ListPRComments(ctx context.Context, owner string, repo string, number int) ([]*github.Comment, error) {
	ret := _mock.Called(ctx, owner, repo, number)

	if len(ret) == 0 {
		panic("no return value specified for ListPRComments")
	}

	var r0 []*github.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) ([]*github.Comment, error)); ok {
		return returnFunc(ctx, owner, repo, number)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) []*github.Comment); ok {
		r0 = returnFunc(ctx, owner, repo, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*github.Comment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = returnFunc(ctx, owner, repo, number)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListPRComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPRComments'
type MockClient_ListPRComments_Call struct {
	*mock.Call
}

// ListPRComments is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - number int
func (_e *MockClient_Expecter) ListPRComments(ctx any, owner any, repo any, number any) *MockClient_ListPRComments_Call {
	return &MockClient_ListPRComments_Call{Call: _e.mock.On("ListPRComments", ctx, owner, repo, number)}
}

func (_c *MockClient_ListPRComments_Call) Run(run func(ctx context.Context, owner string, repo string, number int)) *MockClient_ListPRComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_ListPRComments_Call) Return(comments []*github.Comment, err error) *MockClient_ListPRComments_Call {
	_c.Call.Return(comments, err)
	return _c
}

func (_c *MockClient_ListPRComments_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, number int) ([]*github.Comment, error)) *MockClient_ListPRComments_Call {
	_c.Call.Return(run)
	return _c
}

// ListRepositoryRulesets provides a mock function for the type MockClient
func (_mock *MockClient) ListRepositoryRulesets(ctx context.Context, owner string, repo string) ([]*github.Ruleset, error) {
	ret := _mock.Called(ctx, owner, repo)

	if len(ret) == 0 {
		panic("no return value specified for ListRepositoryRulesets")
	}

	var r0 []*github.Ruleset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]*github.Ruleset, error)); ok {
		return returnFunc(ctx, owner, repo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []*github.Ruleset); ok {
		r0 = returnFunc(ctx, owner, repo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*github.Ruleset)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, owner, repo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListRepositoryRulesets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRepositoryRulesets'
type MockClient_ListRepositoryRulesets_Call struct {
	*mock.Call
}

// ListRepositoryRulesets is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
func (_e *MockClient_Expecter) ListRepositoryRulesets(ctx any, owner any, repo any) *MockClient_ListRepositoryRulesets_Call {
	return &MockClient_ListRepositoryRulesets_Call{Call: _e.mock.On("ListRepositoryRulesets", ctx, owner, repo)}
}

func (_c *MockClient_ListRepositoryRulesets_Call) Run(run func(ctx context.Context, owner string, repo string)) *MockClient_ListRepositoryRulesets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_ListRepositoryRulesets_Call) Return(rulesets []*github.Ruleset, err error) *MockClient_ListRepositoryRulesets_Call {
	_c.Call.Return(rulesets, err)
	return _c
}

func (_c *MockClient_ListRepositoryRulesets_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string) ([]*github.Ruleset, error)) *MockClient_ListRepositoryRulesets_Call {
	_c.Call.Return(run)
	return _c
}

// RateLimitRemaining provides a mock function for the type MockClient
func (_mock *MockClient) RateLimitRemaining(ctx context.Context, installationID int64) (int, int, time.Time, error) {
	ret := _mock.Called(ctx, installationID)

	if len(ret) == 0 {
		panic("no return value specified for RateLimitRemaining")
	}

	var r0 int
	var r1 int
	var r2 time.Time
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (int, int, time.Time, error)); ok {
		return returnFunc(ctx, installationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) int); ok {
		r0 = returnFunc(ctx, installationID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) int); ok {
		r1 = returnFunc(ctx, installationID)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int64) time.Time); ok {
		r2 = returnFunc(ctx, installationID)
	} else {
		r2 = ret.Get(2).(time.Time)
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, int64) error); ok {
		r3 = returnFunc(ctx, installationID)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockClient_RateLimitRemaining_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RateLimitRemaining'
type MockClient_RateLimitRemaining_Call struct {
	*mock.Call
}

// RateLimitRemaining is a helper method to define mock.On call
//   - ctx context.Context
//   - installationID int64
func (_e *MockClient_Expecter) RateLimitRemaining(ctx any, installationID any) *MockClient_RateLimitRemaining_Call {
	return &MockClient_RateLimitRemaining_Call{Call: _e.mock.On("RateLimitRemaining", ctx, installationID)}
}

func (_c *MockClient_RateLimitRemaining_Call) Run(run func(ctx context.Context, installationID int64)) *MockClient_RateLimitRemaining_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_RateLimitRemaining_Call) Return(remaining int, limit int, resetAt time.Time, err error) *MockClient_RateLimitRemaining_Call {
	_c.Call.Return(remaining, limit, resetAt, err)
	return _c
}

func (_c *MockClient_RateLimitRemaining_Call) RunAndReturn(run func(ctx context.Context, installationID int64) (int, int, time.Time, error)) *MockClient_RateLimitRemaining_Call {
	_c.Call.Return(run)
	return _c
}

// SetCustomPropertyValues provides a mock function for the type MockClient
func (_mock *MockClient) SetCustomPropertyValues(ctx context.Context, owner string, repo string, properties []*github.CustomPropertyValue) error {
	ret := _mock.Called(ctx, owner, repo, properties)

	if len(ret) == 0 {
		panic("no return value specified for SetCustomPropertyValues")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []*github.CustomPropertyValue) error); ok {
		r0 = returnFunc(ctx, owner, repo, properties)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_SetCustomPropertyValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCustomPropertyValues'
type MockClient_SetCustomPropertyValues_Call struct {
	*mock.Call
}

// SetCustomPropertyValues is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - properties []*github.CustomPropertyValue
func (_e *MockClient_Expecter) SetCustomPropertyValues(ctx any, owner any, repo any, properties any) *MockClient_SetCustomPropertyValues_Call {
	return &MockClient_SetCustomPropertyValues_Call{Call: _e.mock.On("SetCustomPropertyValues", ctx, owner, repo, properties)}
}

func (_c *MockClient_SetCustomPropertyValues_Call) Run(run func(ctx context.Context, owner string, repo string, properties []*github.CustomPropertyValue)) *MockClient_SetCustomPropertyValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []*github.CustomPropertyValue
		if args[3] != nil {
			arg3 = args[3].([]*github.CustomPropertyValue)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_SetCustomPropertyValues_Call) Return(err error) *MockClient_SetCustomPropertyValues_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_SetCustomPropertyValues_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, properties []*github.CustomPropertyValue) error) *MockClient_SetCustomPropertyValues_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLabel provides a mock function for the type MockClient
func (_mock *MockClient) UpdateLabel(ctx context.Context, owner string, repo string, name string, label *github.Label) error {
	ret := _mock.Called(ctx, owner, repo, name, label)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLabel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, *github.Label) error); ok {
		r0 = returnFunc(ctx, owner, repo, name, label)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_UpdateLabel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLabel'
type MockClient_UpdateLabel_Call struct {
	*mock.Call
}

// UpdateLabel is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - name string
//   - label *github.Label
func (_e *MockClient_Expecter) UpdateLabel(ctx any, owner any, repo any, name any, label any) *MockClient_UpdateLabel_Call {
	return &MockClient_UpdateLabel_Call{Call: _e.mock.On("UpdateLabel", ctx, owner, repo, name, label)}
}

func (_c *MockClient_UpdateLabel_Call) Run(run func(ctx context.Context, owner string, repo string, name string, label *github.Label)) *MockClient_UpdateLabel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *github.Label
		if args[4] != nil {
			arg4 = args[4].(*github.Label)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockClient_UpdateLabel_Call) Return(err error) *MockClient_UpdateLabel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_UpdateLabel_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, name string, label *github.Label) error) *MockClient_UpdateLabel_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePRBranch provides a mock function for the type MockClient
func (_mock *MockClient) UpdatePRBranch(ctx context.Context, owner string, repo string, number int) error {
	ret := _mock.Called(ctx, owner, repo, number)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePRBranch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) error); ok {
		r0 = returnFunc(ctx, owner, repo, number)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_UpdatePRBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePRBranch'
type MockClient_UpdatePRBranch_Call struct {
	*mock.Call
}

// UpdatePRBranch is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - number int
func (_e *MockClient_Expecter) UpdatePRBranch(ctx any, owner any, repo any, number any) *MockClient_UpdatePRBranch_Call {
	return &MockClient_UpdatePRBranch_Call{Call: _e.mock.On("UpdatePRBranch", ctx, owner, repo, number)}
}

func (_c *MockClient_UpdatePRBranch_Call) Run(run func(ctx context.Context, owner string, repo string, number int)) *MockClient_UpdatePRBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_UpdatePRBranch_Call) Return(err error) *MockClient_UpdatePRBranch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_UpdatePRBranch_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, number int) error) *MockClient_UpdatePRBranch_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePullRequest provides a mock function for the type MockClient
func (_mock *MockClient) UpdatePullRequest(ctx context.Context, owner string, repo string, number int, title string, body string) error {
	ret := _mock.Called(ctx, owner, repo, number, title, body)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePullRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, string, string) error); ok {
		r0 = returnFunc(ctx, owner, repo, number, title, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_UpdatePullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePullRequest'
type MockClient_UpdatePullRequest_Call struct {
	*mock.Call
}

// UpdatePullRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - number int
//   - title string
//   - body string
func (_e *MockClient_Expecter) UpdatePullRequest(ctx any, owner any, repo any, number any, title any, body any) *MockClient_UpdatePullRequest_Call {
	return &MockClient_UpdatePullRequest_Call{Call: _e.mock.On("UpdatePullRequest", ctx, owner, repo, number, title, body)}
}

func (_c *MockClient_UpdatePullRequest_Call) Run(run func(ctx context.Context, owner string, repo string, number int, title string, body string)) *MockClient_UpdatePullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockClient_UpdatePullRequest_Call) Return(err error) *MockClient_UpdatePullRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_UpdatePullRequest_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, number int, title string, body string) error) *MockClient_UpdatePullRequest_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRepository provides a mock function for the type MockClient
func (_mock *MockClient) UpdateRepository(ctx context.Context, owner string, repo string, opts *github.RepoUpdateOpts) error {
	ret := _mock.Called(ctx, owner, repo, opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRepository")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *github.RepoUpdateOpts) error); ok {
		r0 = returnFunc(ctx, owner, repo, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_UpdateRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRepository'
type MockClient_UpdateRepository_Call struct {
	*mock.Call
}

// UpdateRepository is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - opts *github.RepoUpdateOpts
func (_e *MockClient_Expecter) UpdateRepository(ctx any, owner any, repo any, opts any) *MockClient_UpdateRepository_Call {
	return &MockClient_UpdateRepository_Call{Call: _e.mock.On("UpdateRepository", ctx, owner, repo, opts)}
}

func (_c *MockClient_UpdateRepository_Call) Run(run func(ctx context.Context, owner string, repo string, opts *github.RepoUpdateOpts)) *MockClient_UpdateRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *github.RepoUpdateOpts
		if args[3] != nil {
			arg3 = args[3].(*github.RepoUpdateOpts)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_UpdateRepository_Call) Return(err error) *MockClient_UpdateRepository_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_UpdateRepository_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, opts *github.RepoUpdateOpts) error) *MockClient_UpdateRepository_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRepositoryRuleset provides a mock function for the type MockClient
func (_mock *MockClient) UpdateRepositoryRuleset(ctx context.Context, owner string, repo string, rulesetID int64, ruleset *github.Ruleset) (*github.Ruleset, error) {
	ret := _mock.Called(ctx, owner, repo, rulesetID, ruleset)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRepositoryRuleset")
	}

	var r0 *github.Ruleset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64, *github.Ruleset) (*github.Ruleset, error)); ok {
		return returnFunc(ctx, owner, repo, rulesetID, ruleset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64, *github.Ruleset) *github.Ruleset); ok {
		r0 = returnFunc(ctx, owner, repo, rulesetID, ruleset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Ruleset)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int64, *github.Ruleset) error); ok {
		r1 = returnFunc(ctx, owner, repo, rulesetID, ruleset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_UpdateRepositoryRuleset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRepositoryRuleset'
type MockClient_UpdateRepositoryRuleset_Call struct {
	*mock.Call
}

// UpdateRepositoryRuleset is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - rulesetID int64
//   - ruleset *github.Ruleset
func (_e *MockClient_Expecter) UpdateRepositoryRuleset(ctx any, owner any, repo any, rulesetID any, ruleset any) *MockClient_UpdateRepositoryRuleset_Call {
	return &MockClient_UpdateRepositoryRuleset_Call{Call: _e.mock.On("UpdateRepositoryRuleset", ctx, owner, repo, rulesetID, ruleset)}
}

func (_c *MockClient_UpdateRepositoryRuleset_Call) Run(run func(ctx context.Context, owner string, repo string, rulesetID int64, ruleset *github.Ruleset)) *MockClient_UpdateRepositoryRuleset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 *github.Ruleset
		if args[4] != nil {
			arg4 = args[4].(*github.Ruleset)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockClient_UpdateRepositoryRuleset_Call) Return(ruleset1 *github.Ruleset, err error) *MockClient_UpdateRepositoryRuleset_Call {
	_c.Call.Return(ruleset1, err)
	return _c
}

func (_c *MockClient_UpdateRepositoryRuleset_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, rulesetID int64, ruleset *github.Ruleset) (*github.Ruleset, error)) *MockClient_UpdateRepositoryRuleset_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertPRComment provides a mock function for the type MockClient
func (_mock *MockClient) UpsertPRComment(ctx context.Context, owner string, repo string, number int, marker string, body string) error {
	ret := _mock.Called(ctx, owner, repo, number, marker, body)

	if len(ret) == 0 {
		panic("no return value specified for UpsertPRComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, string, string) error); ok {
		r0 = returnFunc(ctx, owner, repo, number, marker, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_UpsertPRComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertPRComment'
type MockClient_UpsertPRComment_Call struct {
	*mock.Call
}

// UpsertPRComment is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - number int
//   - marker string
//   - body string
func (_e *MockClient_Expecter) UpsertPRComment(ctx any, owner any, repo any, number any, marker any, body any) *MockClient_UpsertPRComment_Call {
	return &MockClient_UpsertPRComment_Call{Call: _e.mock.On("UpsertPRComment", ctx, owner, repo, number, marker, body)}
}

func (_c *MockClient_UpsertPRComment_Call) Run(run func(ctx context.Context, owner string, repo string, number int, marker string, body string)) *MockClient_UpsertPRComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockClient_UpsertPRComment_Call) Return(err error) *MockClient_UpsertPRComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_UpsertPRComment_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, number int, marker string, body string) error) *MockClient_UpsertPRComment_Call {
	_c.Call.Return(run)
	return _c
}
