// Package monitoring derives the generation model that the dashboard
// and alert generators emit from. See DESIGN-0022 §Config-generated
// monitoring (Finding H, shape H1) and IMPL-0023 Phase 5.
//
// The premise is that a dashboard is a claim about what the running
// system measures, and the only honest source for that claim is the
// same policy the engine loads. A hand-maintained dashboard drifts from
// the config silently: a panel keeps rendering after its rule is
// deleted, and an alert keeps watching a series nothing produces —
// which is exactly how the BudgetTracker's alert survived for months
// watching a counter with no producer (INV-0012 finding A).
//
// # Import discipline
//
// This package imports internal/policy and the standard library. It
// must NOT import:
//
//   - internal/checker — the engine drags in the reconcilers and their
//     promauto registrations, which a read-only CLI has no business
//     performing. Same reasoning as cmd/repo-guardian/report.go.
//   - internal/metrics — for the same registration reason.
//   - the Grafana SDK — that lives in the dashboard sub-package, so
//     DESIGN-0022 OQ5's escape hatch (relocate the generator if the
//     binary-size delta is egregious) stays a package move rather than
//     an untangling. The alert half must keep working in the main
//     binary if that hatch ever fires.
//
// # Determinism
//
// Everything derived from a map is sorted at construction, never at
// emit. The task 5.5 CI drift gate diffs bytes, so one unsorted range
// in an emit path makes the gate flap on nothing.
package monitoring

import (
	"slices"
	"time"
)

// RuleKind is a rule's type, matching the rule_kind column written to
// rule_state and the kind reported by the engine.
//
// Redeclared rather than imported from internal/checker, per the import
// discipline above. TestRuleKinds_MatchTheEngine pins the strings
// against the engine's so the redeclaration cannot drift.
type RuleKind string

// The three kinds. There is deliberately no "unknown" member: a kind
// that is not one of these is a bug in Derive, not a state to render.
const (
	RuleKindFile             RuleKind = "file"
	RuleKindSetting          RuleKind = "setting"
	RuleKindBranchProtection RuleKind = "branch_protection"
)

// Org is one entry from the top-level scope block.
type Org struct {
	// Name is the org name, or the glob pattern verbatim.
	Name string

	// Pattern reports whether Name contains glob metacharacters.
	//
	// Scope orgs are matched with path.Match, so `orgs = ["acme-*"]` is
	// legal, and DESIGN-0022's "one row per configured org" is simply
	// undefined for it — you cannot enumerate the orgs a pattern will
	// match without asking the API. A pattern org therefore cannot
	// carry the silent-org signal: a row that never appears and a row
	// that appears empty are indistinguishable when the row set itself
	// is discovered rather than declared.
	Pattern bool
}

// Rule is one enabled rule, flattened across the three policy slices.
//
// Flattened because every consumer wants one kind-tagged list keyed by
// the rule name — which is the label the posture gauges actually carry
// (repos_actionable{rule_name, org}) — while the policy keeps the three
// kinds in three differently-shaped slices.
type Rule struct {
	Name string
	Kind RuleKind

	// CheckMode is the file-rule mode ("exists", "contains", "exact",
	// "absent"). Empty for setting and branch-protection rules.
	CheckMode string

	// Gated reports whether the rule carries a when { rule_satisfied }
	// block, so it can contribute to rule_gate_closed_total.
	Gated bool

	// Remediates reports whether a setting or branch-protection rule
	// will write back. Always false for file rules, which remediate
	// through a PR rather than a direct write.
	Remediates bool

	// Reconcilers are the attached reconciler type names, sorted.
	Reconcilers []string

	// Orgs are the orgs this rule applies to, already resolved through
	// both scope gates.
	//
	// nil means "every org", which is what legacy mode means and is a
	// materially different statement from an empty slice ("no org"). A
	// strict-mode rule scoped to nothing is a real, reportable
	// condition — it is the config equivalent of the RuleNeverApplies
	// alert — so the two must not collapse.
	Orgs []string
}

// AppliesEverywhere reports whether the rule is unscoped.
func (r *Rule) AppliesEverywhere() bool { return r.Orgs == nil }

// Source is provenance, stamped into generated artifacts.
//
// The drift gate compares generated bytes against committed ones, and
// when it fails the first question is always "generated from what?".
// Without this the answer requires re-deriving the operator's shell.
type Source struct {
	// ConfigPath is the --config value. Empty means built-in defaults.
	ConfigPath string

	// EnvInfluence names environment variables that changed the derived
	// model. Non-empty output from a CI regeneration is a bug, not a
	// diff to accept: policy.BuiltinDefaults reads CUSTOM_PROPERTIES_MODE
	// and applyEnvOverrides runs last over DRY_RUN, SKIP_FORKS,
	// SKIP_ARCHIVED, AUTO_CLOSE_PR, ORPHAN_CLEANUP and SCHEDULE_INTERVAL
	// — every one of which is a mechanism or an alert-window input. A
	// stray variable in a shell would otherwise produce a diff nobody
	// can explain.
	EnvInfluence []string
}

// Model is the whole generation input.
type Model struct {
	// Strict reports whether the policy declared a top-level scope.
	//
	// It decides whether per-org rows are derivable at all: in legacy
	// mode there is no org list anywhere in the policy, so the row set
	// has to be discovered from the series instead of declared.
	Strict bool

	// Orgs are the configured orgs, sorted by name. Empty in legacy
	// mode.
	Orgs []Org

	// Rules are the enabled rules, sorted by (kind, name).
	Rules []Rule

	// Mechanisms are the configured features that produce series.
	Mechanisms Mechanisms

	// SweepInterval is guardian.schedule_interval, the cadence alert
	// windows have to clear.
	SweepInterval time.Duration

	Source Source
}

// OrgNames returns the configured org names, sorted.
func (m *Model) OrgNames() []string {
	out := make([]string, 0, len(m.Orgs))
	for _, o := range m.Orgs {
		out = append(out, o.Name)
	}

	return out
}

// RulesFor returns the rules that apply to org, in Rules order.
//
// In legacy mode every rule applies to every org, which is why an
// unscoped rule carries a nil Orgs rather than an empty one.
func (m *Model) RulesFor(org string) []Rule {
	out := make([]Rule, 0, len(m.Rules))

	for i := range m.Rules {
		if m.Rules[i].AppliesEverywhere() {
			out = append(out, m.Rules[i])

			continue
		}

		for _, name := range m.Rules[i].Orgs {
			if name == org {
				out = append(out, m.Rules[i])

				break
			}
		}
	}

	return out
}

// RuleNames returns the names of every rule of the given kinds, sorted
// and deduplicated, plus whether any exist.
//
// The false return is the caller's instruction to omit the panel
// entirely. It is not the same as an empty selector: a matcher built
// from no names matches nothing useful, and one built by skipping the
// matcher matches EVERY rule — which is how a "forbidden files" panel
// ends up charting codeowners.
//
// Deduplicated across kinds because it has to be: rule-name uniqueness
// is validated within each kind but not across them, so a `rule "file"
// "x"` and a `rule "setting" "x"` both emit rule_name="x". Derive
// rejects that collision, so this is belt and braces.
func (m *Model) RuleNames(kinds ...RuleKind) ([]string, bool) {
	seen := make(map[string]struct{}, len(m.Rules))
	out := make([]string, 0, len(m.Rules))

	for i := range m.Rules {
		if !matchesKind(m.Rules[i].Kind, kinds) {
			continue
		}

		if _, dup := seen[m.Rules[i].Name]; dup {
			continue
		}

		seen[m.Rules[i].Name] = struct{}{}

		out = append(out, m.Rules[i].Name)
	}

	// Rules is already sorted by (kind, name), so a multi-kind query
	// would otherwise come out grouped by kind rather than by name.
	slices.Sort(out)

	return out, len(out) > 0
}

// matchesKind reports whether kind is in kinds. An empty kinds list
// matches everything, so RuleNames() with no argument means "all".
func matchesKind(kind RuleKind, kinds []RuleKind) bool {
	if len(kinds) == 0 {
		return true
	}

	for _, k := range kinds {
		if k == kind {
			return true
		}
	}

	return false
}
