// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockScheduler creates a new instance of MockScheduler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScheduler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScheduler {
	mock := &MockScheduler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScheduler is an autogenerated mock type for the Scheduler type
type MockScheduler struct {
	mock.Mock
}

type MockScheduler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScheduler) EXPECT() *MockScheduler_Expecter {
	return &MockScheduler_Expecter{mock: &_m.Mock}
}

// Schedule provides a mock function for the type MockScheduler
func (_mock *MockScheduler) Schedule(ctx context.Context, name string, interval time.Duration, handler func(context.Context) error) error {
	ret := _mock.Called(ctx, name, interval, handler)

	if len(ret) == 0 {
		panic("no return value specified for Schedule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration, func(context.Context) error) error); ok {
		r0 = returnFunc(ctx, name, interval, handler)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockScheduler_Schedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Schedule'
type MockScheduler_Schedule_Call struct {
	*mock.Call
}

// Schedule is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - interval time.Duration
//   - handler func(context.Context) error
func (_e *MockScheduler_Expecter) Schedule(ctx any, name any, interval any, handler any) *MockScheduler_Schedule_Call {
	return &MockScheduler_Schedule_Call{Call: _e.mock.On("Schedule", ctx, name, interval, handler)}
}

func (_c *MockScheduler_Schedule_Call) Run(run func(ctx context.Context, name string, interval time.Duration, handler func(context.Context) error)) *MockScheduler_Schedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		var arg3 func(context.Context) error
		if args[3] != nil {
			arg3 = args[3].(func(context.Context) error)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockScheduler_Schedule_Call) Return(err error) *MockScheduler_Schedule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockScheduler_Schedule_Call) RunAndReturn(run func(ctx context.Context, name string, interval time.Duration, handler func(context.Context) error) error) *MockScheduler_Schedule_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockScheduler
func (_mock *MockScheduler) Stop() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockScheduler_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockScheduler_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockScheduler_Expecter) Stop() *MockScheduler_Stop_Call {
	return &MockScheduler_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockScheduler_Stop_Call) Run(run func()) *MockScheduler_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockScheduler_Stop_Call) Return(err error) *MockScheduler_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockScheduler_Stop_Call) RunAndReturn(run func() error) *MockScheduler_Stop_Call {
	_c.Call.Return(run)
	return _c
}
