// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/donaldgifford/repo-guardian/internal/store"
)

// NewMockReader creates a new instance of MockReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReader {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockReader is an autogenerated mock type for the Reader type
type MockReader struct {
	mock.Mock
}

type MockReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReader) EXPECT() *MockReader_Expecter {
	return &MockReader_Expecter{mock: &_m.Mock}
}

// GetRepository provides a mock function for the type MockReader
func (_mock *MockReader) GetRepository(ctx context.Context, id int64) (*store.Repository, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRepository")
	}

	var r0 *store.Repository
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*store.Repository, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *store.Repository); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Repository)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReader_GetRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepository'
type MockReader_GetRepository_Call struct {
	*mock.Call
}

// GetRepository is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockReader_Expecter) GetRepository(ctx any, id any) *MockReader_GetRepository_Call {
	return &MockReader_GetRepository_Call{Call: _e.mock.On("GetRepository", ctx, id)}
}

func (_c *MockReader_GetRepository_Call) Run(run func(ctx context.Context, id int64)) *MockReader_GetRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReader_GetRepository_Call) Return(repository *store.Repository, err error) *MockReader_GetRepository_Call {
	_c.Call.Return(repository, err)
	return _c
}

func (_c *MockReader_GetRepository_Call) RunAndReturn(run func(ctx context.Context, id int64) (*store.Repository, error)) *MockReader_GetRepository_Call {
	_c.Call.Return(run)
	return _c
}

// ListActiveRepositories provides a mock function for the type MockReader
func (_mock *MockReader) ListActiveRepositories(ctx context.Context, afterID int64, limit int) ([]store.Repository, error) {
	ret := _mock.Called(ctx, afterID, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveRepositories")
	}

	var r0 []store.Repository
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int) ([]store.Repository, error)); ok {
		return returnFunc(ctx, afterID, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int) []store.Repository); ok {
		r0 = returnFunc(ctx, afterID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.Repository)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int) error); ok {
		r1 = returnFunc(ctx, afterID, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReader_ListActiveRepositories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActiveRepositories'
type MockReader_ListActiveRepositories_Call struct {
	*mock.Call
}

// ListActiveRepositories is a helper method to define mock.On call
//   - ctx context.Context
//   - afterID int64
//   - limit int
func (_e *MockReader_Expecter) ListActiveRepositories(ctx any, afterID any, limit any) *MockReader_ListActiveRepositories_Call {
	return &MockReader_ListActiveRepositories_Call{Call: _e.mock.On("ListActiveRepositories", ctx, afterID, limit)}
}

func (_c *MockReader_ListActiveRepositories_Call) Run(run func(ctx context.Context, afterID int64, limit int)) *MockReader_ListActiveRepositories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReader_ListActiveRepositories_Call) Return(repositorys []store.Repository, err error) *MockReader_ListActiveRepositories_Call {
	_c.Call.Return(repositorys, err)
	return _c
}

func (_c *MockReader_ListActiveRepositories_Call) RunAndReturn(run func(ctx context.Context, afterID int64, limit int) ([]store.Repository, error)) *MockReader_ListActiveRepositories_Call {
	_c.Call.Return(run)
	return _c
}
