// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"

	"github.com/donaldgifford/repo-guardian/internal/store"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockStore
func (_mock *MockStore) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockStore_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockStore_Expecter) Close() *MockStore_Close_Call {
	return &MockStore_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockStore_Close_Call) Run(run func()) *MockStore_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_Close_Call) Return(err error) *MockStore_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Close_Call) RunAndReturn(run func() error) *MockStore_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepoState provides a mock function for the type MockStore
func (_mock *MockStore) GetRepoState(ctx context.Context, installationID int64, owner string, repo string) (*store.RepoState, error) {
	ret := _mock.Called(ctx, installationID, owner, repo)

	if len(ret) == 0 {
		panic("no return value specified for GetRepoState")
	}

	var r0 *store.RepoState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string) (*store.RepoState, error)); ok {
		return returnFunc(ctx, installationID, owner, repo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string) *store.RepoState); ok {
		r0 = returnFunc(ctx, installationID, owner, repo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.RepoState)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, string) error); ok {
		r1 = returnFunc(ctx, installationID, owner, repo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetRepoState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepoState'
type MockStore_GetRepoState_Call struct {
	*mock.Call
}

// GetRepoState is a helper method to define mock.On call
//   - ctx context.Context
//   - installationID int64
//   - owner string
//   - repo string
func (_e *MockStore_Expecter) GetRepoState(ctx any, installationID any, owner any, repo any) *MockStore_GetRepoState_Call {
	return &MockStore_GetRepoState_Call{Call: _e.mock.On("GetRepoState", ctx, installationID, owner, repo)}
}

func (_c *MockStore_GetRepoState_Call) Run(run func(ctx context.Context, installationID int64, owner string, repo string)) *MockStore_GetRepoState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStore_GetRepoState_Call) Return(repoState *store.RepoState, err error) *MockStore_GetRepoState_Call {
	_c.Call.Return(repoState, err)
	return _c
}

func (_c *MockStore_GetRepoState_Call) RunAndReturn(run func(ctx context.Context, installationID int64, owner string, repo string) (*store.RepoState, error)) *MockStore_GetRepoState_Call {
	_c.Call.Return(run)
	return _c
}

// StaleRepos provides a mock function for the type MockStore
func (_mock *MockStore) StaleRepos(ctx context.Context, freshness time.Duration, currentPolicyVersion string, limit int) ([]store.RepoState, error) {
	ret := _mock.Called(ctx, freshness, currentPolicyVersion, limit)

	if len(ret) == 0 {
		panic("no return value specified for StaleRepos")
	}

	var r0 []store.RepoState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration, string, int) ([]store.RepoState, error)); ok {
		return returnFunc(ctx, freshness, currentPolicyVersion, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration, string, int) []store.RepoState); ok {
		r0 = returnFunc(ctx, freshness, currentPolicyVersion, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.RepoState)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Duration, string, int) error); ok {
		r1 = returnFunc(ctx, freshness, currentPolicyVersion, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_StaleRepos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StaleRepos'
type MockStore_StaleRepos_Call struct {
	*mock.Call
}

// StaleRepos is a helper method to define mock.On call
//   - ctx context.Context
//   - freshness time.Duration
//   - currentPolicyVersion string
//   - limit int
func (_e *MockStore_Expecter) StaleRepos(ctx any, freshness any, currentPolicyVersion any, limit any) *MockStore_StaleRepos_Call {
	return &MockStore_StaleRepos_Call{Call: _e.mock.On("StaleRepos", ctx, freshness, currentPolicyVersion, limit)}
}

func (_c *MockStore_StaleRepos_Call) Run(run func(ctx context.Context, freshness time.Duration, currentPolicyVersion string, limit int)) *MockStore_StaleRepos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStore_StaleRepos_Call) Return(repoStates []store.RepoState, err error) *MockStore_StaleRepos_Call {
	_c.Call.Return(repoStates, err)
	return _c
}

func (_c *MockStore_StaleRepos_Call) RunAndReturn(run func(ctx context.Context, freshness time.Duration, currentPolicyVersion string, limit int) ([]store.RepoState, error)) *MockStore_StaleRepos_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRepoState provides a mock function for the type MockStore
func (_mock *MockStore) UpdateRepoState(ctx context.Context, s *store.RepoState) error {
	ret := _mock.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRepoState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *store.RepoState) error); ok {
		r0 = returnFunc(ctx, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_UpdateRepoState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRepoState'
type MockStore_UpdateRepoState_Call struct {
	*mock.Call
}

// UpdateRepoState is a helper method to define mock.On call
//   - ctx context.Context
//   - s *store.RepoState
func (_e *MockStore_Expecter) UpdateRepoState(ctx any, s any) *MockStore_UpdateRepoState_Call {
	return &MockStore_UpdateRepoState_Call{Call: _e.mock.On("UpdateRepoState", ctx, s)}
}

func (_c *MockStore_UpdateRepoState_Call) Run(run func(ctx context.Context, s *store.RepoState)) *MockStore_UpdateRepoState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *store.RepoState
		if args[1] != nil {
			arg1 = args[1].(*store.RepoState)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_UpdateRepoState_Call) Return(err error) *MockStore_UpdateRepoState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_UpdateRepoState_Call) RunAndReturn(run func(ctx context.Context, s *store.RepoState) error) *MockStore_UpdateRepoState_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertIfMissing provides a mock function for the type MockStore
func (_mock *MockStore) UpsertIfMissing(ctx context.Context, s *store.RepoState) (bool, error) {
	ret := _mock.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for UpsertIfMissing")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *store.RepoState) (bool, error)); ok {
		return returnFunc(ctx, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *store.RepoState) bool); ok {
		r0 = returnFunc(ctx, s)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *store.RepoState) error); ok {
		r1 = returnFunc(ctx, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_UpsertIfMissing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertIfMissing'
type MockStore_UpsertIfMissing_Call struct {
	*mock.Call
}

// UpsertIfMissing is a helper method to define mock.On call
//   - ctx context.Context
//   - s *store.RepoState
func (_e *MockStore_Expecter) UpsertIfMissing(ctx any, s any) *MockStore_UpsertIfMissing_Call {
	return &MockStore_UpsertIfMissing_Call{Call: _e.mock.On("UpsertIfMissing", ctx, s)}
}

func (_c *MockStore_UpsertIfMissing_Call) Run(run func(ctx context.Context, s *store.RepoState)) *MockStore_UpsertIfMissing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *store.RepoState
		if args[1] != nil {
			arg1 = args[1].(*store.RepoState)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_UpsertIfMissing_Call) Return(created bool, err error) *MockStore_UpsertIfMissing_Call {
	_c.Call.Return(created, err)
	return _c
}

func (_c *MockStore_UpsertIfMissing_Call) RunAndReturn(run func(ctx context.Context, s *store.RepoState) (bool, error)) *MockStore_UpsertIfMissing_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertRuleStates provides a mock function for the type MockStore
func (_mock *MockStore) UpsertRuleStates(ctx context.Context, installationID int64, owner string, repo string, states []store.RuleState) error {
	ret := _mock.Called(ctx, installationID, owner, repo, states)

	if len(ret) == 0 {
		panic("no return value specified for UpsertRuleStates")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string, []store.RuleState) error); ok {
		r0 = returnFunc(ctx, installationID, owner, repo, states)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_UpsertRuleStates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertRuleStates'
type MockStore_UpsertRuleStates_Call struct {
	*mock.Call
}

// UpsertRuleStates is a helper method to define mock.On call
//   - ctx context.Context
//   - installationID int64
//   - owner string
//   - repo string
//   - states []store.RuleState
func (_e *MockStore_Expecter) UpsertRuleStates(ctx any, installationID any, owner any, repo any, states any) *MockStore_UpsertRuleStates_Call {
	return &MockStore_UpsertRuleStates_Call{Call: _e.mock.On("UpsertRuleStates", ctx, installationID, owner, repo, states)}
}

func (_c *MockStore_UpsertRuleStates_Call) Run(run func(ctx context.Context, installationID int64, owner string, repo string, states []store.RuleState)) *MockStore_UpsertRuleStates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []store.RuleState
		if args[4] != nil {
			arg4 = args[4].([]store.RuleState)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockStore_UpsertRuleStates_Call) Return(err error) *MockStore_UpsertRuleStates_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_UpsertRuleStates_Call) RunAndReturn(run func(ctx context.Context, installationID int64, owner string, repo string, states []store.RuleState) error) *MockStore_UpsertRuleStates_Call {
	_c.Call.Return(run)
	return _c
}
