// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	store "github.com/donaldgifford/repo-guardian/internal/store"

	time "time"
)

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockStore) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockStore_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockStore_Expecter) Close() *MockStore_Close_Call {
	return &MockStore_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockStore_Close_Call) Run(run func()) *MockStore_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_Close_Call) Return(_a0 error) *MockStore_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_Close_Call) RunAndReturn(run func() error) *MockStore_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepoState provides a mock function with given fields: ctx, installationID, owner, repo
func (_m *MockStore) GetRepoState(ctx context.Context, installationID int64, owner string, repo string) (*store.RepoState, error) {
	ret := _m.Called(ctx, installationID, owner, repo)

	if len(ret) == 0 {
		panic("no return value specified for GetRepoState")
	}

	var r0 *store.RepoState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string) (*store.RepoState, error)); ok {
		return rf(ctx, installationID, owner, repo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string) *store.RepoState); ok {
		r0 = rf(ctx, installationID, owner, repo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.RepoState)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, string) error); ok {
		r1 = rf(ctx, installationID, owner, repo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetRepoState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepoState'
type MockStore_GetRepoState_Call struct {
	*mock.Call
}

// GetRepoState is a helper method to define mock.On call
//   - ctx context.Context
//   - installationID int64
//   - owner string
//   - repo string
func (_e *MockStore_Expecter) GetRepoState(ctx interface{}, installationID interface{}, owner interface{}, repo interface{}) *MockStore_GetRepoState_Call {
	return &MockStore_GetRepoState_Call{Call: _e.mock.On("GetRepoState", ctx, installationID, owner, repo)}
}

func (_c *MockStore_GetRepoState_Call) Run(run func(ctx context.Context, installationID int64, owner string, repo string)) *MockStore_GetRepoState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockStore_GetRepoState_Call) Return(_a0 *store.RepoState, _a1 error) *MockStore_GetRepoState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetRepoState_Call) RunAndReturn(run func(context.Context, int64, string, string) (*store.RepoState, error)) *MockStore_GetRepoState_Call {
	_c.Call.Return(run)
	return _c
}

// StaleRepos provides a mock function with given fields: ctx, freshness, currentPolicyVersion, limit
func (_m *MockStore) StaleRepos(ctx context.Context, freshness time.Duration, currentPolicyVersion string, limit int) ([]store.RepoState, error) {
	ret := _m.Called(ctx, freshness, currentPolicyVersion, limit)

	if len(ret) == 0 {
		panic("no return value specified for StaleRepos")
	}

	var r0 []store.RepoState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration, string, int) ([]store.RepoState, error)); ok {
		return rf(ctx, freshness, currentPolicyVersion, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration, string, int) []store.RepoState); ok {
		r0 = rf(ctx, freshness, currentPolicyVersion, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.RepoState)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Duration, string, int) error); ok {
		r1 = rf(ctx, freshness, currentPolicyVersion, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_StaleRepos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StaleRepos'
type MockStore_StaleRepos_Call struct {
	*mock.Call
}

// StaleRepos is a helper method to define mock.On call
//   - ctx context.Context
//   - freshness time.Duration
//   - currentPolicyVersion string
//   - limit int
func (_e *MockStore_Expecter) StaleRepos(ctx interface{}, freshness interface{}, currentPolicyVersion interface{}, limit interface{}) *MockStore_StaleRepos_Call {
	return &MockStore_StaleRepos_Call{Call: _e.mock.On("StaleRepos", ctx, freshness, currentPolicyVersion, limit)}
}

func (_c *MockStore_StaleRepos_Call) Run(run func(ctx context.Context, freshness time.Duration, currentPolicyVersion string, limit int)) *MockStore_StaleRepos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Duration), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *MockStore_StaleRepos_Call) Return(_a0 []store.RepoState, _a1 error) *MockStore_StaleRepos_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_StaleRepos_Call) RunAndReturn(run func(context.Context, time.Duration, string, int) ([]store.RepoState, error)) *MockStore_StaleRepos_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRepoState provides a mock function with given fields: ctx, s
func (_m *MockStore) UpdateRepoState(ctx context.Context, s *store.RepoState) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRepoState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *store.RepoState) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_UpdateRepoState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRepoState'
type MockStore_UpdateRepoState_Call struct {
	*mock.Call
}

// UpdateRepoState is a helper method to define mock.On call
//   - ctx context.Context
//   - s *store.RepoState
func (_e *MockStore_Expecter) UpdateRepoState(ctx interface{}, s interface{}) *MockStore_UpdateRepoState_Call {
	return &MockStore_UpdateRepoState_Call{Call: _e.mock.On("UpdateRepoState", ctx, s)}
}

func (_c *MockStore_UpdateRepoState_Call) Run(run func(ctx context.Context, s *store.RepoState)) *MockStore_UpdateRepoState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*store.RepoState))
	})
	return _c
}

func (_c *MockStore_UpdateRepoState_Call) Return(_a0 error) *MockStore_UpdateRepoState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_UpdateRepoState_Call) RunAndReturn(run func(context.Context, *store.RepoState) error) *MockStore_UpdateRepoState_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
