// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"

	"github.com/donaldgifford/repo-guardian/internal/store"
)

// NewMockWriter creates a new instance of MockWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWriter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockWriter is an autogenerated mock type for the Writer type
type MockWriter struct {
	mock.Mock
}

type MockWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWriter) EXPECT() *MockWriter_Expecter {
	return &MockWriter_Expecter{mock: &_m.Mock}
}

// BootstrapPending provides a mock function for the type MockWriter
func (_mock *MockWriter) BootstrapPending(ctx context.Context) (bool, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BootstrapPending")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWriter_BootstrapPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BootstrapPending'
type MockWriter_BootstrapPending_Call struct {
	*mock.Call
}

// BootstrapPending is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWriter_Expecter) BootstrapPending(ctx any) *MockWriter_BootstrapPending_Call {
	return &MockWriter_BootstrapPending_Call{Call: _e.mock.On("BootstrapPending", ctx)}
}

func (_c *MockWriter_BootstrapPending_Call) Run(run func(ctx context.Context)) *MockWriter_BootstrapPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWriter_BootstrapPending_Call) Return(b bool, err error) *MockWriter_BootstrapPending_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockWriter_BootstrapPending_Call) RunAndReturn(run func(ctx context.Context) (bool, error)) *MockWriter_BootstrapPending_Call {
	_c.Call.Return(run)
	return _c
}

// ClearBootstrapPending provides a mock function for the type MockWriter
func (_mock *MockWriter) ClearBootstrapPending(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ClearBootstrapPending")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWriter_ClearBootstrapPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearBootstrapPending'
type MockWriter_ClearBootstrapPending_Call struct {
	*mock.Call
}

// ClearBootstrapPending is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWriter_Expecter) ClearBootstrapPending(ctx any) *MockWriter_ClearBootstrapPending_Call {
	return &MockWriter_ClearBootstrapPending_Call{Call: _e.mock.On("ClearBootstrapPending", ctx)}
}

func (_c *MockWriter_ClearBootstrapPending_Call) Run(run func(ctx context.Context)) *MockWriter_ClearBootstrapPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWriter_ClearBootstrapPending_Call) Return(err error) *MockWriter_ClearBootstrapPending_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWriter_ClearBootstrapPending_Call) RunAndReturn(run func(ctx context.Context) error) *MockWriter_ClearBootstrapPending_Call {
	_c.Call.Return(run)
	return _c
}

// CompletePolicyRollout provides a mock function for the type MockWriter
func (_mock *MockWriter) CompletePolicyRollout(ctx context.Context, version string) error {
	ret := _mock.Called(ctx, version)

	if len(ret) == 0 {
		panic("no return value specified for CompletePolicyRollout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, version)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWriter_CompletePolicyRollout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompletePolicyRollout'
type MockWriter_CompletePolicyRollout_Call struct {
	*mock.Call
}

// CompletePolicyRollout is a helper method to define mock.On call
//   - ctx context.Context
//   - version string
func (_e *MockWriter_Expecter) CompletePolicyRollout(ctx any, version any) *MockWriter_CompletePolicyRollout_Call {
	return &MockWriter_CompletePolicyRollout_Call{Call: _e.mock.On("CompletePolicyRollout", ctx, version)}
}

func (_c *MockWriter_CompletePolicyRollout_Call) Run(run func(ctx context.Context, version string)) *MockWriter_CompletePolicyRollout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWriter_CompletePolicyRollout_Call) Return(err error) *MockWriter_CompletePolicyRollout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWriter_CompletePolicyRollout_Call) RunAndReturn(run func(ctx context.Context, version string) error) *MockWriter_CompletePolicyRollout_Call {
	_c.Call.Return(run)
	return _c
}

// InsertComplianceSnapshot provides a mock function for the type MockWriter
func (_mock *MockWriter) InsertComplianceSnapshot(ctx context.Context, at time.Time) (int, error) {
	ret := _mock.Called(ctx, at)

	if len(ret) == 0 {
		panic("no return value specified for InsertComplianceSnapshot")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) (int, error)); ok {
		return returnFunc(ctx, at)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) int); ok {
		r0 = returnFunc(ctx, at)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, at)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWriter_InsertComplianceSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertComplianceSnapshot'
type MockWriter_InsertComplianceSnapshot_Call struct {
	*mock.Call
}

// InsertComplianceSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - at time.Time
func (_e *MockWriter_Expecter) InsertComplianceSnapshot(ctx any, at any) *MockWriter_InsertComplianceSnapshot_Call {
	return &MockWriter_InsertComplianceSnapshot_Call{Call: _e.mock.On("InsertComplianceSnapshot", ctx, at)}
}

func (_c *MockWriter_InsertComplianceSnapshot_Call) Run(run func(ctx context.Context, at time.Time)) *MockWriter_InsertComplianceSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWriter_InsertComplianceSnapshot_Call) Return(n int, err error) *MockWriter_InsertComplianceSnapshot_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockWriter_InsertComplianceSnapshot_Call) RunAndReturn(run func(ctx context.Context, at time.Time) (int, error)) *MockWriter_InsertComplianceSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// MarkInstallationRemoved provides a mock function for the type MockWriter
func (_mock *MockWriter) MarkInstallationRemoved(ctx context.Context, installationID int64, at time.Time) error {
	ret := _mock.Called(ctx, installationID, at)

	if len(ret) == 0 {
		panic("no return value specified for MarkInstallationRemoved")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time) error); ok {
		r0 = returnFunc(ctx, installationID, at)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWriter_MarkInstallationRemoved_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkInstallationRemoved'
type MockWriter_MarkInstallationRemoved_Call struct {
	*mock.Call
}

// MarkInstallationRemoved is a helper method to define mock.On call
//   - ctx context.Context
//   - installationID int64
//   - at time.Time
func (_e *MockWriter_Expecter) MarkInstallationRemoved(ctx any, installationID any, at any) *MockWriter_MarkInstallationRemoved_Call {
	return &MockWriter_MarkInstallationRemoved_Call{Call: _e.mock.On("MarkInstallationRemoved", ctx, installationID, at)}
}

func (_c *MockWriter_MarkInstallationRemoved_Call) Run(run func(ctx context.Context, installationID int64, at time.Time)) *MockWriter_MarkInstallationRemoved_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWriter_MarkInstallationRemoved_Call) Return(err error) *MockWriter_MarkInstallationRemoved_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWriter_MarkInstallationRemoved_Call) RunAndReturn(run func(ctx context.Context, installationID int64, at time.Time) error) *MockWriter_MarkInstallationRemoved_Call {
	_c.Call.Return(run)
	return _c
}

// Park provides a mock function for the type MockWriter
func (_mock *MockWriter) Park(ctx context.Context, repoID int64, reason store.ParkReason, clearFindings bool) error {
	ret := _mock.Called(ctx, repoID, reason, clearFindings)

	if len(ret) == 0 {
		panic("no return value specified for Park")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, store.ParkReason, bool) error); ok {
		r0 = returnFunc(ctx, repoID, reason, clearFindings)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWriter_Park_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Park'
type MockWriter_Park_Call struct {
	*mock.Call
}

// Park is a helper method to define mock.On call
//   - ctx context.Context
//   - repoID int64
//   - reason store.ParkReason
//   - clearFindings bool
func (_e *MockWriter_Expecter) Park(ctx any, repoID any, reason any, clearFindings any) *MockWriter_Park_Call {
	return &MockWriter_Park_Call{Call: _e.mock.On("Park", ctx, repoID, reason, clearFindings)}
}

func (_c *MockWriter_Park_Call) Run(run func(ctx context.Context, repoID int64, reason store.ParkReason, clearFindings bool)) *MockWriter_Park_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 store.ParkReason
		if args[2] != nil {
			arg2 = args[2].(store.ParkReason)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockWriter_Park_Call) Return(err error) *MockWriter_Park_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWriter_Park_Call) RunAndReturn(run func(ctx context.Context, repoID int64, reason store.ParkReason, clearFindings bool) error) *MockWriter_Park_Call {
	_c.Call.Return(run)
	return _c
}

// PruneChecks provides a mock function for the type MockWriter
func (_mock *MockWriter) PruneChecks(ctx context.Context, before time.Time) (int64, error) {
	ret := _mock.Called(ctx, before)

	if len(ret) == 0 {
		panic("no return value specified for PruneChecks")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return returnFunc(ctx, before)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = returnFunc(ctx, before)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, before)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWriter_PruneChecks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PruneChecks'
type MockWriter_PruneChecks_Call struct {
	*mock.Call
}

// PruneChecks is a helper method to define mock.On call
//   - ctx context.Context
//   - before time.Time
func (_e *MockWriter_Expecter) PruneChecks(ctx any, before any) *MockWriter_PruneChecks_Call {
	return &MockWriter_PruneChecks_Call{Call: _e.mock.On("PruneChecks", ctx, before)}
}

func (_c *MockWriter_PruneChecks_Call) Run(run func(ctx context.Context, before time.Time)) *MockWriter_PruneChecks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWriter_PruneChecks_Call) Return(n int64, err error) *MockWriter_PruneChecks_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockWriter_PruneChecks_Call) RunAndReturn(run func(ctx context.Context, before time.Time) (int64, error)) *MockWriter_PruneChecks_Call {
	_c.Call.Return(run)
	return _c
}

// RecordCheck provides a mock function for the type MockWriter
func (_mock *MockWriter) RecordCheck(ctx context.Context, c *store.CheckRecord) (*store.CheckApplied, error) {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for RecordCheck")
	}

	var r0 *store.CheckApplied
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *store.CheckRecord) (*store.CheckApplied, error)); ok {
		return returnFunc(ctx, c)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *store.CheckRecord) *store.CheckApplied); ok {
		r0 = returnFunc(ctx, c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.CheckApplied)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *store.CheckRecord) error); ok {
		r1 = returnFunc(ctx, c)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWriter_RecordCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordCheck'
type MockWriter_RecordCheck_Call struct {
	*mock.Call
}

// RecordCheck is a helper method to define mock.On call
//   - ctx context.Context
//   - c *store.CheckRecord
func (_e *MockWriter_Expecter) RecordCheck(ctx any, c any) *MockWriter_RecordCheck_Call {
	return &MockWriter_RecordCheck_Call{Call: _e.mock.On("RecordCheck", ctx, c)}
}

func (_c *MockWriter_RecordCheck_Call) Run(run func(ctx context.Context, c *store.CheckRecord)) *MockWriter_RecordCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *store.CheckRecord
		if args[1] != nil {
			arg1 = args[1].(*store.CheckRecord)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWriter_RecordCheck_Call) Return(checkApplied *store.CheckApplied, err error) *MockWriter_RecordCheck_Call {
	_c.Call.Return(checkApplied, err)
	return _c
}

func (_c *MockWriter_RecordCheck_Call) RunAndReturn(run func(ctx context.Context, c *store.CheckRecord) (*store.CheckApplied, error)) *MockWriter_RecordCheck_Call {
	_c.Call.Return(run)
	return _c
}

// RecordCheckError provides a mock function for the type MockWriter
func (_mock *MockWriter) RecordCheckError(ctx context.Context, c *store.CheckErrorRecord) error {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for RecordCheckError")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *store.CheckErrorRecord) error); ok {
		r0 = returnFunc(ctx, c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWriter_RecordCheckError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordCheckError'
type MockWriter_RecordCheckError_Call struct {
	*mock.Call
}

// RecordCheckError is a helper method to define mock.On call
//   - ctx context.Context
//   - c *store.CheckErrorRecord
func (_e *MockWriter_Expecter) RecordCheckError(ctx any, c any) *MockWriter_RecordCheckError_Call {
	return &MockWriter_RecordCheckError_Call{Call: _e.mock.On("RecordCheckError", ctx, c)}
}

func (_c *MockWriter_RecordCheckError_Call) Run(run func(ctx context.Context, c *store.CheckErrorRecord)) *MockWriter_RecordCheckError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *store.CheckErrorRecord
		if args[1] != nil {
			arg1 = args[1].(*store.CheckErrorRecord)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWriter_RecordCheckError_Call) Return(err error) *MockWriter_RecordCheckError_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWriter_RecordCheckError_Call) RunAndReturn(run func(ctx context.Context, c *store.CheckErrorRecord) error) *MockWriter_RecordCheckError_Call {
	_c.Call.Return(run)
	return _c
}

// RecordPolicyVersion provides a mock function for the type MockWriter
func (_mock *MockWriter) RecordPolicyVersion(ctx context.Context, version string, summary store.PolicySummary) (bool, error) {
	ret := _mock.Called(ctx, version, summary)

	if len(ret) == 0 {
		panic("no return value specified for RecordPolicyVersion")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, store.PolicySummary) (bool, error)); ok {
		return returnFunc(ctx, version, summary)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, store.PolicySummary) bool); ok {
		r0 = returnFunc(ctx, version, summary)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, store.PolicySummary) error); ok {
		r1 = returnFunc(ctx, version, summary)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWriter_RecordPolicyVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordPolicyVersion'
type MockWriter_RecordPolicyVersion_Call struct {
	*mock.Call
}

// RecordPolicyVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - version string
//   - summary store.PolicySummary
func (_e *MockWriter_Expecter) RecordPolicyVersion(ctx any, version any, summary any) *MockWriter_RecordPolicyVersion_Call {
	return &MockWriter_RecordPolicyVersion_Call{Call: _e.mock.On("RecordPolicyVersion", ctx, version, summary)}
}

func (_c *MockWriter_RecordPolicyVersion_Call) Run(run func(ctx context.Context, version string, summary store.PolicySummary)) *MockWriter_RecordPolicyVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 store.PolicySummary
		if args[2] != nil {
			arg2 = args[2].(store.PolicySummary)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWriter_RecordPolicyVersion_Call) Return(firstSeen bool, err error) *MockWriter_RecordPolicyVersion_Call {
	_c.Call.Return(firstSeen, err)
	return _c
}

func (_c *MockWriter_RecordPolicyVersion_Call) RunAndReturn(run func(ctx context.Context, version string, summary store.PolicySummary) (bool, error)) *MockWriter_RecordPolicyVersion_Call {
	_c.Call.Return(run)
	return _c
}

// RecordServiceRun provides a mock function for the type MockWriter
func (_mock *MockWriter) RecordServiceRun(ctx context.Context, run *store.ServiceRun) error {
	ret := _mock.Called(ctx, run)

	if len(ret) == 0 {
		panic("no return value specified for RecordServiceRun")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *store.ServiceRun) error); ok {
		r0 = returnFunc(ctx, run)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWriter_RecordServiceRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordServiceRun'
type MockWriter_RecordServiceRun_Call struct {
	*mock.Call
}

// RecordServiceRun is a helper method to define mock.On call
//   - ctx context.Context
//   - run *store.ServiceRun
func (_e *MockWriter_Expecter) RecordServiceRun(ctx any, run any) *MockWriter_RecordServiceRun_Call {
	return &MockWriter_RecordServiceRun_Call{Call: _e.mock.On("RecordServiceRun", ctx, run)}
}

func (_c *MockWriter_RecordServiceRun_Call) Run(run func(ctx context.Context, run *store.ServiceRun)) *MockWriter_RecordServiceRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *store.ServiceRun
		if args[1] != nil {
			arg1 = args[1].(*store.ServiceRun)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWriter_RecordServiceRun_Call) Return(err error) *MockWriter_RecordServiceRun_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWriter_RecordServiceRun_Call) RunAndReturn(run func(ctx context.Context, run *store.ServiceRun) error) *MockWriter_RecordServiceRun_Call {
	_c.Call.Return(run)
	return _c
}

// StageCheck provides a mock function for the type MockWriter
func (_mock *MockWriter) StageCheck(ctx context.Context, c *store.CheckRecord) error {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for StageCheck")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *store.CheckRecord) error); ok {
		r0 = returnFunc(ctx, c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWriter_StageCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StageCheck'
type MockWriter_StageCheck_Call struct {
	*mock.Call
}

// StageCheck is a helper method to define mock.On call
//   - ctx context.Context
//   - c *store.CheckRecord
func (_e *MockWriter_Expecter) StageCheck(ctx any, c any) *MockWriter_StageCheck_Call {
	return &MockWriter_StageCheck_Call{Call: _e.mock.On("StageCheck", ctx, c)}
}

func (_c *MockWriter_StageCheck_Call) Run(run func(ctx context.Context, c *store.CheckRecord)) *MockWriter_StageCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *store.CheckRecord
		if args[1] != nil {
			arg1 = args[1].(*store.CheckRecord)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWriter_StageCheck_Call) Return(err error) *MockWriter_StageCheck_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWriter_StageCheck_Call) RunAndReturn(run func(ctx context.Context, c *store.CheckRecord) error) *MockWriter_StageCheck_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertDiscovered provides a mock function for the type MockWriter
func (_mock *MockWriter) UpsertDiscovered(ctx context.Context, r *store.DiscoveredRepo) (store.UpsertResult, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for UpsertDiscovered")
	}

	var r0 store.UpsertResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *store.DiscoveredRepo) (store.UpsertResult, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *store.DiscoveredRepo) store.UpsertResult); ok {
		r0 = returnFunc(ctx, r)
	} else {
		r0 = ret.Get(0).(store.UpsertResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *store.DiscoveredRepo) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWriter_UpsertDiscovered_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertDiscovered'
type MockWriter_UpsertDiscovered_Call struct {
	*mock.Call
}

// UpsertDiscovered is a helper method to define mock.On call
//   - ctx context.Context
//   - r *store.DiscoveredRepo
func (_e *MockWriter_Expecter) UpsertDiscovered(ctx any, r any) *MockWriter_UpsertDiscovered_Call {
	return &MockWriter_UpsertDiscovered_Call{Call: _e.mock.On("UpsertDiscovered", ctx, r)}
}

func (_c *MockWriter_UpsertDiscovered_Call) Run(run func(ctx context.Context, r *store.DiscoveredRepo)) *MockWriter_UpsertDiscovered_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *store.DiscoveredRepo
		if args[1] != nil {
			arg1 = args[1].(*store.DiscoveredRepo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWriter_UpsertDiscovered_Call) Return(upsertResult store.UpsertResult, err error) *MockWriter_UpsertDiscovered_Call {
	_c.Call.Return(upsertResult, err)
	return _c
}

func (_c *MockWriter_UpsertDiscovered_Call) RunAndReturn(run func(ctx context.Context, r *store.DiscoveredRepo) (store.UpsertResult, error)) *MockWriter_UpsertDiscovered_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertInstallation provides a mock function for the type MockWriter
func (_mock *MockWriter) UpsertInstallation(ctx context.Context, in store.Installation) error {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for UpsertInstallation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.Installation) error); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWriter_UpsertInstallation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertInstallation'
type MockWriter_UpsertInstallation_Call struct {
	*mock.Call
}

// UpsertInstallation is a helper method to define mock.On call
//   - ctx context.Context
//   - in store.Installation
func (_e *MockWriter_Expecter) UpsertInstallation(ctx any, in any) *MockWriter_UpsertInstallation_Call {
	return &MockWriter_UpsertInstallation_Call{Call: _e.mock.On("UpsertInstallation", ctx, in)}
}

func (_c *MockWriter_UpsertInstallation_Call) Run(run func(ctx context.Context, in store.Installation)) *MockWriter_UpsertInstallation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 store.Installation
		if args[1] != nil {
			arg1 = args[1].(store.Installation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWriter_UpsertInstallation_Call) Return(err error) *MockWriter_UpsertInstallation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWriter_UpsertInstallation_Call) RunAndReturn(run func(ctx context.Context, in store.Installation) error) *MockWriter_UpsertInstallation_Call {
	_c.Call.Return(run)
	return _c
}
