// Package postgres implements the v2 store (V2Store, APIReader) against
// PostgreSQL via pgx/v5 + pgxpool. The v2 schema is a goose chain under
// migrations_v2/, applied only by `repo-guardian migrate`; queries are
// generated by sqlc into sqlcdb/.
//
// The v1 golang-migrate chain under migrations/ is kept as a test
// fixture (backfill and rollback tests replay it) until IMPL-0029
// retires the rc schema. The v1 Store implementation itself is gone
// (IMPL-0028 Phase 1).
//
// All queries are parameterized.
package postgres

import (
	"time"

	"github.com/donaldgifford/repo-guardian/internal/metrics"
)

// observeQuery records the duration of a single store query under
// (operation, outcome). outcome is "ok" if err is nil, "error"
// otherwise.
func observeQuery(operation string, start time.Time, err error) {
	outcome := "ok"
	if err != nil {
		outcome = "error"
	}

	metrics.StoreQuerySeconds.
		WithLabelValues(operation, outcome).
		Observe(time.Since(start).Seconds())
}
