// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/donaldgifford/repo-guardian/internal/control"
)

// NewMockPRObserver creates a new instance of MockPRObserver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPRObserver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPRObserver {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockPRObserver{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockPRObserver is an autogenerated mock type for the PRObserver type
type MockPRObserver struct {
	mock.Mock
}

type MockPRObserver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPRObserver) EXPECT() *MockPRObserver_Expecter {
	return &MockPRObserver_Expecter{mock: &_m.Mock}
}

// GetPullRequest provides a mock function for the type MockPRObserver
func (_mock *MockPRObserver) GetPullRequest(ctx context.Context, number int) (*control.PullRequest, error) {
	ret := _mock.Called(ctx, number)

	if len(ret) == 0 {
		panic("no return value specified for GetPullRequest")
	}

	var r0 *control.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*control.PullRequest, error)); ok {
		return returnFunc(ctx, number)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *control.PullRequest); ok {
		r0 = returnFunc(ctx, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*control.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, number)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPRObserver_GetPullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPullRequest'
type MockPRObserver_GetPullRequest_Call struct {
	*mock.Call
}

// GetPullRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - number int
func (_e *MockPRObserver_Expecter) GetPullRequest(ctx any, number any) *MockPRObserver_GetPullRequest_Call {
	return &MockPRObserver_GetPullRequest_Call{Call: _e.mock.On("GetPullRequest", ctx, number)}
}

func (_c *MockPRObserver_GetPullRequest_Call) Run(run func(ctx context.Context, number int)) *MockPRObserver_GetPullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPRObserver_GetPullRequest_Call) Return(pullRequest *control.PullRequest, err error) *MockPRObserver_GetPullRequest_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockPRObserver_GetPullRequest_Call) RunAndReturn(run func(ctx context.Context, number int) (*control.PullRequest, error)) *MockPRObserver_GetPullRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetRef provides a mock function for the type MockPRObserver
func (_mock *MockPRObserver) GetRef(ctx context.Context, branch string) (string, bool, error) {
	ret := _mock.Called(ctx, branch)

	if len(ret) == 0 {
		panic("no return value specified for GetRef")
	}

	var r0 string
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, bool, error)); ok {
		return returnFunc(ctx, branch)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, branch)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(ctx, branch)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, branch)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockPRObserver_GetRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRef'
type MockPRObserver_GetRef_Call struct {
	*mock.Call
}

// GetRef is a helper method to define mock.On call
//   - ctx context.Context
//   - branch string
func (_e *MockPRObserver_Expecter) GetRef(ctx any, branch any) *MockPRObserver_GetRef_Call {
	return &MockPRObserver_GetRef_Call{Call: _e.mock.On("GetRef", ctx, branch)}
}

func (_c *MockPRObserver_GetRef_Call) Run(run func(ctx context.Context, branch string)) *MockPRObserver_GetRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPRObserver_GetRef_Call) Return(sha string, exists bool, err error) *MockPRObserver_GetRef_Call {
	_c.Call.Return(sha, exists, err)
	return _c
}

func (_c *MockPRObserver_GetRef_Call) RunAndReturn(run func(ctx context.Context, branch string) (string, bool, error)) *MockPRObserver_GetRef_Call {
	_c.Call.Return(run)
	return _c
}

// ListCommits provides a mock function for the type MockPRObserver
func (_mock *MockPRObserver) ListCommits(ctx context.Context, branch string) ([]control.Commit, error) {
	ret := _mock.Called(ctx, branch)

	if len(ret) == 0 {
		panic("no return value specified for ListCommits")
	}

	var r0 []control.Commit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]control.Commit, error)); ok {
		return returnFunc(ctx, branch)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []control.Commit); ok {
		r0 = returnFunc(ctx, branch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]control.Commit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, branch)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPRObserver_ListCommits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCommits'
type MockPRObserver_ListCommits_Call struct {
	*mock.Call
}

// ListCommits is a helper method to define mock.On call
//   - ctx context.Context
//   - branch string
func (_e *MockPRObserver_Expecter) ListCommits(ctx any, branch any) *MockPRObserver_ListCommits_Call {
	return &MockPRObserver_ListCommits_Call{Call: _e.mock.On("ListCommits", ctx, branch)}
}

func (_c *MockPRObserver_ListCommits_Call) Run(run func(ctx context.Context, branch string)) *MockPRObserver_ListCommits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPRObserver_ListCommits_Call) Return(commits []control.Commit, err error) *MockPRObserver_ListCommits_Call {
	_c.Call.Return(commits, err)
	return _c
}

func (_c *MockPRObserver_ListCommits_Call) RunAndReturn(run func(ctx context.Context, branch string) ([]control.Commit, error)) *MockPRObserver_ListCommits_Call {
	_c.Call.Return(run)
	return _c
}

// ListPullRequests provides a mock function for the type MockPRObserver
func (_mock *MockPRObserver) ListPullRequests(ctx context.Context, headPrefix string) ([]control.PullRequest, error) {
	ret := _mock.Called(ctx, headPrefix)

	if len(ret) == 0 {
		panic("no return value specified for ListPullRequests")
	}

	var r0 []control.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]control.PullRequest, error)); ok {
		return returnFunc(ctx, headPrefix)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []control.PullRequest); ok {
		r0 = returnFunc(ctx, headPrefix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]control.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, headPrefix)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPRObserver_ListPullRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPullRequests'
type MockPRObserver_ListPullRequests_Call struct {
	*mock.Call
}

// ListPullRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - headPrefix string
func (_e *MockPRObserver_Expecter) ListPullRequests(ctx any, headPrefix any) *MockPRObserver_ListPullRequests_Call {
	return &MockPRObserver_ListPullRequests_Call{Call: _e.mock.On("ListPullRequests", ctx, headPrefix)}
}

func (_c *MockPRObserver_ListPullRequests_Call) Run(run func(ctx context.Context, headPrefix string)) *MockPRObserver_ListPullRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPRObserver_ListPullRequests_Call) Return(pullRequests []control.PullRequest, err error) *MockPRObserver_ListPullRequests_Call {
	_c.Call.Return(pullRequests, err)
	return _c
}

func (_c *MockPRObserver_ListPullRequests_Call) RunAndReturn(run func(ctx context.Context, headPrefix string) ([]control.PullRequest, error)) *MockPRObserver_ListPullRequests_Call {
	_c.Call.Return(run)
	return _c
}
