// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/donaldgifford/repo-guardian/internal/control"
)

// NewMockReader creates a new instance of MockReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReader {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockReader is an autogenerated mock type for the Reader type
type MockReader struct {
	mock.Mock
}

type MockReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReader) EXPECT() *MockReader_Expecter {
	return &MockReader_Expecter{mock: &_m.Mock}
}

// GetContents provides a mock function for the type MockReader
func (_mock *MockReader) GetContents(ctx context.Context, path string) ([]byte, string, bool, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for GetContents")
	}

	var r0 []byte
	var r1 string
	var r2 bool
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, string, bool, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) bool); ok {
		r2 = returnFunc(ctx, path)
	} else {
		r2 = ret.Get(2).(bool)
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, string) error); ok {
		r3 = returnFunc(ctx, path)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockReader_GetContents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContents'
type MockReader_GetContents_Call struct {
	*mock.Call
}

// GetContents is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockReader_Expecter) GetContents(ctx any, path any) *MockReader_GetContents_Call {
	return &MockReader_GetContents_Call{Call: _e.mock.On("GetContents", ctx, path)}
}

func (_c *MockReader_GetContents_Call) Run(run func(ctx context.Context, path string)) *MockReader_GetContents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReader_GetContents_Call) Return(content []byte, blobSHA string, found bool, err error) *MockReader_GetContents_Call {
	_c.Call.Return(content, blobSHA, found, err)
	return _c
}

func (_c *MockReader_GetContents_Call) RunAndReturn(run func(ctx context.Context, path string) ([]byte, string, bool, error)) *MockReader_GetContents_Call {
	_c.Call.Return(run)
	return _c
}

// GetCustomProperties provides a mock function for the type MockReader
func (_mock *MockReader) GetCustomProperties(ctx context.Context) (map[string]*string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomProperties")
	}

	var r0 map[string]*string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string]*string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]*string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReader_GetCustomProperties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomProperties'
type MockReader_GetCustomProperties_Call struct {
	*mock.Call
}

// GetCustomProperties is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReader_Expecter) GetCustomProperties(ctx any) *MockReader_GetCustomProperties_Call {
	return &MockReader_GetCustomProperties_Call{Call: _e.mock.On("GetCustomProperties", ctx)}
}

func (_c *MockReader_GetCustomProperties_Call) Run(run func(ctx context.Context)) *MockReader_GetCustomProperties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReader_GetCustomProperties_Call) Return(stringToS map[string]*string, err error) *MockReader_GetCustomProperties_Call {
	_c.Call.Return(stringToS, err)
	return _c
}

func (_c *MockReader_GetCustomProperties_Call) RunAndReturn(run func(ctx context.Context) (map[string]*string, error)) *MockReader_GetCustomProperties_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepository provides a mock function for the type MockReader
func (_mock *MockReader) GetRepository(ctx context.Context) (control.RepositorySettings, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRepository")
	}

	var r0 control.RepositorySettings
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (control.RepositorySettings, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) control.RepositorySettings); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(control.RepositorySettings)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReader_GetRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepository'
type MockReader_GetRepository_Call struct {
	*mock.Call
}

// GetRepository is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReader_Expecter) GetRepository(ctx any) *MockReader_GetRepository_Call {
	return &MockReader_GetRepository_Call{Call: _e.mock.On("GetRepository", ctx)}
}

func (_c *MockReader_GetRepository_Call) Run(run func(ctx context.Context)) *MockReader_GetRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReader_GetRepository_Call) Return(repositorySettings control.RepositorySettings, err error) *MockReader_GetRepository_Call {
	_c.Call.Return(repositorySettings, err)
	return _c
}

func (_c *MockReader_GetRepository_Call) RunAndReturn(run func(ctx context.Context) (control.RepositorySettings, error)) *MockReader_GetRepository_Call {
	_c.Call.Return(run)
	return _c
}

// ListDirectory provides a mock function for the type MockReader
func (_mock *MockReader) ListDirectory(ctx context.Context, path string) ([]string, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for ListDirectory")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReader_ListDirectory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDirectory'
type MockReader_ListDirectory_Call struct {
	*mock.Call
}

// ListDirectory is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockReader_Expecter) ListDirectory(ctx any, path any) *MockReader_ListDirectory_Call {
	return &MockReader_ListDirectory_Call{Call: _e.mock.On("ListDirectory", ctx, path)}
}

func (_c *MockReader_ListDirectory_Call) Run(run func(ctx context.Context, path string)) *MockReader_ListDirectory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReader_ListDirectory_Call) Return(strings []string, err error) *MockReader_ListDirectory_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockReader_ListDirectory_Call) RunAndReturn(run func(ctx context.Context, path string) ([]string, error)) *MockReader_ListDirectory_Call {
	_c.Call.Return(run)
	return _c
}

// ListLabels provides a mock function for the type MockReader
func (_mock *MockReader) ListLabels(ctx context.Context) ([]control.Label, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListLabels")
	}

	var r0 []control.Label
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]control.Label, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []control.Label); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]control.Label)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReader_ListLabels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListLabels'
type MockReader_ListLabels_Call struct {
	*mock.Call
}

// ListLabels is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReader_Expecter) ListLabels(ctx any) *MockReader_ListLabels_Call {
	return &MockReader_ListLabels_Call{Call: _e.mock.On("ListLabels", ctx)}
}

func (_c *MockReader_ListLabels_Call) Run(run func(ctx context.Context)) *MockReader_ListLabels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReader_ListLabels_Call) Return(labels []control.Label, err error) *MockReader_ListLabels_Call {
	_c.Call.Return(labels, err)
	return _c
}

func (_c *MockReader_ListLabels_Call) RunAndReturn(run func(ctx context.Context) ([]control.Label, error)) *MockReader_ListLabels_Call {
	_c.Call.Return(run)
	return _c
}

// ListRulesets provides a mock function for the type MockReader
func (_mock *MockReader) ListRulesets(ctx context.Context) ([]control.Ruleset, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRulesets")
	}

	var r0 []control.Ruleset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]control.Ruleset, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []control.Ruleset); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]control.Ruleset)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReader_ListRulesets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRulesets'
type MockReader_ListRulesets_Call struct {
	*mock.Call
}

// ListRulesets is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReader_Expecter) ListRulesets(ctx any) *MockReader_ListRulesets_Call {
	return &MockReader_ListRulesets_Call{Call: _e.mock.On("ListRulesets", ctx)}
}

func (_c *MockReader_ListRulesets_Call) Run(run func(ctx context.Context)) *MockReader_ListRulesets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReader_ListRulesets_Call) Return(rulesets []control.Ruleset, err error) *MockReader_ListRulesets_Call {
	_c.Call.Return(rulesets, err)
	return _c
}

func (_c *MockReader_ListRulesets_Call) RunAndReturn(run func(ctx context.Context) ([]control.Ruleset, error)) *MockReader_ListRulesets_Call {
	_c.Call.Return(run)
	return _c
}

// OrgPropertySchema provides a mock function for the type MockReader
func (_mock *MockReader) OrgPropertySchema(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for OrgPropertySchema")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReader_OrgPropertySchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrgPropertySchema'
type MockReader_OrgPropertySchema_Call struct {
	*mock.Call
}

// OrgPropertySchema is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReader_Expecter) OrgPropertySchema(ctx any) *MockReader_OrgPropertySchema_Call {
	return &MockReader_OrgPropertySchema_Call{Call: _e.mock.On("OrgPropertySchema", ctx)}
}

func (_c *MockReader_OrgPropertySchema_Call) Run(run func(ctx context.Context)) *MockReader_OrgPropertySchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReader_OrgPropertySchema_Call) Return(strings []string, err error) *MockReader_OrgPropertySchema_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockReader_OrgPropertySchema_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockReader_OrgPropertySchema_Call {
	_c.Call.Return(run)
	return _c
}
