// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/donaldgifford/repo-guardian/internal/control"
)

// NewMockWriter creates a new instance of MockWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWriter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockWriter is an autogenerated mock type for the Writer type
type MockWriter struct {
	mock.Mock
}

type MockWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWriter) EXPECT() *MockWriter_Expecter {
	return &MockWriter_Expecter{mock: &_m.Mock}
}

// ClosePullRequest provides a mock function for the type MockWriter
func (_mock *MockWriter) ClosePullRequest(ctx context.Context, number int) error {
	ret := _mock.Called(ctx, number)

	if len(ret) == 0 {
		panic("no return value specified for ClosePullRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, number)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWriter_ClosePullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClosePullRequest'
type MockWriter_ClosePullRequest_Call struct {
	*mock.Call
}

// ClosePullRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - number int
func (_e *MockWriter_Expecter) ClosePullRequest(ctx any, number any) *MockWriter_ClosePullRequest_Call {
	return &MockWriter_ClosePullRequest_Call{Call: _e.mock.On("ClosePullRequest", ctx, number)}
}

func (_c *MockWriter_ClosePullRequest_Call) Run(run func(ctx context.Context, number int)) *MockWriter_ClosePullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWriter_ClosePullRequest_Call) Return(err error) *MockWriter_ClosePullRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWriter_ClosePullRequest_Call) RunAndReturn(run func(ctx context.Context, number int) error) *MockWriter_ClosePullRequest_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function for the type MockWriter
func (_mock *MockWriter) Commit(ctx context.Context, branch string, baseSHA string, changes []control.FileChange, message string) (string, error) {
	ret := _mock.Called(ctx, branch, baseSHA, changes, message)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []control.FileChange, string) (string, error)); ok {
		return returnFunc(ctx, branch, baseSHA, changes, message)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []control.FileChange, string) string); ok {
		r0 = returnFunc(ctx, branch, baseSHA, changes, message)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []control.FileChange, string) error); ok {
		r1 = returnFunc(ctx, branch, baseSHA, changes, message)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWriter_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockWriter_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
//   - branch string
//   - baseSHA string
//   - changes []control.FileChange
//   - message string
func (_e *MockWriter_Expecter) Commit(ctx any, branch any, baseSHA any, changes any, message any) *MockWriter_Commit_Call {
	return &MockWriter_Commit_Call{Call: _e.mock.On("Commit", ctx, branch, baseSHA, changes, message)}
}

func (_c *MockWriter_Commit_Call) Run(run func(ctx context.Context, branch string, baseSHA string, changes []control.FileChange, message string)) *MockWriter_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []control.FileChange
		if args[3] != nil {
			arg3 = args[3].([]control.FileChange)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockWriter_Commit_Call) Return(headSHA string, err error) *MockWriter_Commit_Call {
	_c.Call.Return(headSHA, err)
	return _c
}

func (_c *MockWriter_Commit_Call) RunAndReturn(run func(ctx context.Context, branch string, baseSHA string, changes []control.FileChange, message string) (string, error)) *MockWriter_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePullRequest provides a mock function for the type MockWriter
func (_mock *MockWriter) CreatePullRequest(ctx context.Context, head string, base string, title string, body string) (*control.PullRequest, error) {
	ret := _mock.Called(ctx, head, base, title, body)

	if len(ret) == 0 {
		panic("no return value specified for CreatePullRequest")
	}

	var r0 *control.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*control.PullRequest, error)); ok {
		return returnFunc(ctx, head, base, title, body)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) *control.PullRequest); ok {
		r0 = returnFunc(ctx, head, base, title, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*control.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, head, base, title, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWriter_CreatePullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePullRequest'
type MockWriter_CreatePullRequest_Call struct {
	*mock.Call
}

// CreatePullRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - head string
//   - base string
//   - title string
//   - body string
func (_e *MockWriter_Expecter) CreatePullRequest(ctx any, head any, base any, title any, body any) *MockWriter_CreatePullRequest_Call {
	return &MockWriter_CreatePullRequest_Call{Call: _e.mock.On("CreatePullRequest", ctx, head, base, title, body)}
}

func (_c *MockWriter_CreatePullRequest_Call) Run(run func(ctx context.Context, head string, base string, title string, body string)) *MockWriter_CreatePullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockWriter_CreatePullRequest_Call) Return(pullRequest *control.PullRequest, err error) *MockWriter_CreatePullRequest_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockWriter_CreatePullRequest_Call) RunAndReturn(run func(ctx context.Context, head string, base string, title string, body string) (*control.PullRequest, error)) *MockWriter_CreatePullRequest_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRef provides a mock function for the type MockWriter
func (_mock *MockWriter) CreateRef(ctx context.Context, branch string, sha string) error {
	ret := _mock.Called(ctx, branch, sha)

	if len(ret) == 0 {
		panic("no return value specified for CreateRef")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, branch, sha)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWriter_CreateRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRef'
type MockWriter_CreateRef_Call struct {
	*mock.Call
}

// CreateRef is a helper method to define mock.On call
//   - ctx context.Context
//   - branch string
//   - sha string
func (_e *MockWriter_Expecter) CreateRef(ctx any, branch any, sha any) *MockWriter_CreateRef_Call {
	return &MockWriter_CreateRef_Call{Call: _e.mock.On("CreateRef", ctx, branch, sha)}
}

func (_c *MockWriter_CreateRef_Call) Run(run func(ctx context.Context, branch string, sha string)) *MockWriter_CreateRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWriter_CreateRef_Call) Return(err error) *MockWriter_CreateRef_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWriter_CreateRef_Call) RunAndReturn(run func(ctx context.Context, branch string, sha string) error) *MockWriter_CreateRef_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLabel provides a mock function for the type MockWriter
func (_mock *MockWriter) DeleteLabel(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLabel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWriter_DeleteLabel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLabel'
type MockWriter_DeleteLabel_Call struct {
	*mock.Call
}

// DeleteLabel is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockWriter_Expecter) DeleteLabel(ctx any, name any) *MockWriter_DeleteLabel_Call {
	return &MockWriter_DeleteLabel_Call{Call: _e.mock.On("DeleteLabel", ctx, name)}
}

func (_c *MockWriter_DeleteLabel_Call) Run(run func(ctx context.Context, name string)) *MockWriter_DeleteLabel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWriter_DeleteLabel_Call) Return(err error) *MockWriter_DeleteLabel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWriter_DeleteLabel_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockWriter_DeleteLabel_Call {
	_c.Call.Return(run)
	return _c
}

// SetCustomProperties provides a mock function for the type MockWriter
func (_mock *MockWriter) SetCustomProperties(ctx context.Context, props map[string]*string) error {
	ret := _mock.Called(ctx, props)

	if len(ret) == 0 {
		panic("no return value specified for SetCustomProperties")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]*string) error); ok {
		r0 = returnFunc(ctx, props)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWriter_SetCustomProperties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCustomProperties'
type MockWriter_SetCustomProperties_Call struct {
	*mock.Call
}

// SetCustomProperties is a helper method to define mock.On call
//   - ctx context.Context
//   - props map[string]*string
func (_e *MockWriter_Expecter) SetCustomProperties(ctx any, props any) *MockWriter_SetCustomProperties_Call {
	return &MockWriter_SetCustomProperties_Call{Call: _e.mock.On("SetCustomProperties", ctx, props)}
}

func (_c *MockWriter_SetCustomProperties_Call) Run(run func(ctx context.Context, props map[string]*string)) *MockWriter_SetCustomProperties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]*string
		if args[1] != nil {
			arg1 = args[1].(map[string]*string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWriter_SetCustomProperties_Call) Return(err error) *MockWriter_SetCustomProperties_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWriter_SetCustomProperties_Call) RunAndReturn(run func(ctx context.Context, props map[string]*string) error) *MockWriter_SetCustomProperties_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBranch provides a mock function for the type MockWriter
func (_mock *MockWriter) UpdateBranch(ctx context.Context, number int, expectedHeadSHA string) error {
	ret := _mock.Called(ctx, number, expectedHeadSHA)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBranch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, number, expectedHeadSHA)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWriter_UpdateBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBranch'
type MockWriter_UpdateBranch_Call struct {
	*mock.Call
}

// UpdateBranch is a helper method to define mock.On call
//   - ctx context.Context
//   - number int
//   - expectedHeadSHA string
func (_e *MockWriter_Expecter) UpdateBranch(ctx any, number any, expectedHeadSHA any) *MockWriter_UpdateBranch_Call {
	return &MockWriter_UpdateBranch_Call{Call: _e.mock.On("UpdateBranch", ctx, number, expectedHeadSHA)}
}

func (_c *MockWriter_UpdateBranch_Call) Run(run func(ctx context.Context, number int, expectedHeadSHA string)) *MockWriter_UpdateBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWriter_UpdateBranch_Call) Return(err error) *MockWriter_UpdateBranch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWriter_UpdateBranch_Call) RunAndReturn(run func(ctx context.Context, number int, expectedHeadSHA string) error) *MockWriter_UpdateBranch_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePullRequest provides a mock function for the type MockWriter
func (_mock *MockWriter) UpdatePullRequest(ctx context.Context, number int, title string, body string) error {
	ret := _mock.Called(ctx, number, title, body)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePullRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, string) error); ok {
		r0 = returnFunc(ctx, number, title, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWriter_UpdatePullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePullRequest'
type MockWriter_UpdatePullRequest_Call struct {
	*mock.Call
}

// UpdatePullRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - number int
//   - title string
//   - body string
func (_e *MockWriter_Expecter) UpdatePullRequest(ctx any, number any, title any, body any) *MockWriter_UpdatePullRequest_Call {
	return &MockWriter_UpdatePullRequest_Call{Call: _e.mock.On("UpdatePullRequest", ctx, number, title, body)}
}

func (_c *MockWriter_UpdatePullRequest_Call) Run(run func(ctx context.Context, number int, title string, body string)) *MockWriter_UpdatePullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockWriter_UpdatePullRequest_Call) Return(err error) *MockWriter_UpdatePullRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWriter_UpdatePullRequest_Call) RunAndReturn(run func(ctx context.Context, number int, title string, body string) error) *MockWriter_UpdatePullRequest_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePullRequestBase provides a mock function for the type MockWriter
func (_mock *MockWriter) UpdatePullRequestBase(ctx context.Context, number int, base string) error {
	ret := _mock.Called(ctx, number, base)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePullRequestBase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, number, base)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWriter_UpdatePullRequestBase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePullRequestBase'
type MockWriter_UpdatePullRequestBase_Call struct {
	*mock.Call
}

// UpdatePullRequestBase is a helper method to define mock.On call
//   - ctx context.Context
//   - number int
//   - base string
func (_e *MockWriter_Expecter) UpdatePullRequestBase(ctx any, number any, base any) *MockWriter_UpdatePullRequestBase_Call {
	return &MockWriter_UpdatePullRequestBase_Call{Call: _e.mock.On("UpdatePullRequestBase", ctx, number, base)}
}

func (_c *MockWriter_UpdatePullRequestBase_Call) Run(run func(ctx context.Context, number int, base string)) *MockWriter_UpdatePullRequestBase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWriter_UpdatePullRequestBase_Call) Return(err error) *MockWriter_UpdatePullRequestBase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWriter_UpdatePullRequestBase_Call) RunAndReturn(run func(ctx context.Context, number int, base string) error) *MockWriter_UpdatePullRequestBase_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRepository provides a mock function for the type MockWriter
func (_mock *MockWriter) UpdateRepository(ctx context.Context, settings control.RepositorySettings) error {
	ret := _mock.Called(ctx, settings)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRepository")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, control.RepositorySettings) error); ok {
		r0 = returnFunc(ctx, settings)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWriter_UpdateRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRepository'
type MockWriter_UpdateRepository_Call struct {
	*mock.Call
}

// UpdateRepository is a helper method to define mock.On call
//   - ctx context.Context
//   - settings control.RepositorySettings
func (_e *MockWriter_Expecter) UpdateRepository(ctx any, settings any) *MockWriter_UpdateRepository_Call {
	return &MockWriter_UpdateRepository_Call{Call: _e.mock.On("UpdateRepository", ctx, settings)}
}

func (_c *MockWriter_UpdateRepository_Call) Run(run func(ctx context.Context, settings control.RepositorySettings)) *MockWriter_UpdateRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 control.RepositorySettings
		if args[1] != nil {
			arg1 = args[1].(control.RepositorySettings)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWriter_UpdateRepository_Call) Return(err error) *MockWriter_UpdateRepository_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWriter_UpdateRepository_Call) RunAndReturn(run func(ctx context.Context, settings control.RepositorySettings) error) *MockWriter_UpdateRepository_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertLabel provides a mock function for the type MockWriter
func (_mock *MockWriter) UpsertLabel(ctx context.Context, l control.Label) error {
	ret := _mock.Called(ctx, l)

	if len(ret) == 0 {
		panic("no return value specified for UpsertLabel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, control.Label) error); ok {
		r0 = returnFunc(ctx, l)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWriter_UpsertLabel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertLabel'
type MockWriter_UpsertLabel_Call struct {
	*mock.Call
}

// UpsertLabel is a helper method to define mock.On call
//   - ctx context.Context
//   - l control.Label
func (_e *MockWriter_Expecter) UpsertLabel(ctx any, l any) *MockWriter_UpsertLabel_Call {
	return &MockWriter_UpsertLabel_Call{Call: _e.mock.On("UpsertLabel", ctx, l)}
}

func (_c *MockWriter_UpsertLabel_Call) Run(run func(ctx context.Context, l control.Label)) *MockWriter_UpsertLabel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 control.Label
		if args[1] != nil {
			arg1 = args[1].(control.Label)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWriter_UpsertLabel_Call) Return(err error) *MockWriter_UpsertLabel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWriter_UpsertLabel_Call) RunAndReturn(run func(ctx context.Context, l control.Label) error) *MockWriter_UpsertLabel_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertPRComment provides a mock function for the type MockWriter
func (_mock *MockWriter) UpsertPRComment(ctx context.Context, number int, marker string, body string) error {
	ret := _mock.Called(ctx, number, marker, body)

	if len(ret) == 0 {
		panic("no return value specified for UpsertPRComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, string) error); ok {
		r0 = returnFunc(ctx, number, marker, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWriter_UpsertPRComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertPRComment'
type MockWriter_UpsertPRComment_Call struct {
	*mock.Call
}

// UpsertPRComment is a helper method to define mock.On call
//   - ctx context.Context
//   - number int
//   - marker string
//   - body string
func (_e *MockWriter_Expecter) UpsertPRComment(ctx any, number any, marker any, body any) *MockWriter_UpsertPRComment_Call {
	return &MockWriter_UpsertPRComment_Call{Call: _e.mock.On("UpsertPRComment", ctx, number, marker, body)}
}

func (_c *MockWriter_UpsertPRComment_Call) Run(run func(ctx context.Context, number int, marker string, body string)) *MockWriter_UpsertPRComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockWriter_UpsertPRComment_Call) Return(err error) *MockWriter_UpsertPRComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWriter_UpsertPRComment_Call) RunAndReturn(run func(ctx context.Context, number int, marker string, body string) error) *MockWriter_UpsertPRComment_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertRuleset provides a mock function for the type MockWriter
func (_mock *MockWriter) UpsertRuleset(ctx context.Context, rs control.Ruleset) error {
	ret := _mock.Called(ctx, rs)

	if len(ret) == 0 {
		panic("no return value specified for UpsertRuleset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, control.Ruleset) error); ok {
		r0 = returnFunc(ctx, rs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWriter_UpsertRuleset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertRuleset'
type MockWriter_UpsertRuleset_Call struct {
	*mock.Call
}

// UpsertRuleset is a helper method to define mock.On call
//   - ctx context.Context
//   - rs control.Ruleset
func (_e *MockWriter_Expecter) UpsertRuleset(ctx any, rs any) *MockWriter_UpsertRuleset_Call {
	return &MockWriter_UpsertRuleset_Call{Call: _e.mock.On("UpsertRuleset", ctx, rs)}
}

func (_c *MockWriter_UpsertRuleset_Call) Run(run func(ctx context.Context, rs control.Ruleset)) *MockWriter_UpsertRuleset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 control.Ruleset
		if args[1] != nil {
			arg1 = args[1].(control.Ruleset)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWriter_UpsertRuleset_Call) Return(err error) *MockWriter_UpsertRuleset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWriter_UpsertRuleset_Call) RunAndReturn(run func(ctx context.Context, rs control.Ruleset) error) *MockWriter_UpsertRuleset_Call {
	_c.Call.Return(run)
	return _c
}
