apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "repo-guardian.fullname" . }}-templates
  labels:
    {{- include "repo-guardian.labels" . | nindent 4 }}
data:
  {{- if .Values.templates.codeowners }}
  CODEOWNERS.tmpl: |
    {{- .Values.templates.codeowners | nindent 4 }}
  {{- end }}
  {{- if .Values.templates.dependabot }}
  dependabot.yml.tmpl: |
    {{- .Values.templates.dependabot | nindent 4 }}
  {{- end }}
  {{- if .Values.templates.renovate }}
  renovate.json.tmpl: |
    {{- .Values.templates.renovate | nindent 4 }}
  {{- end }}
