{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "repo-guardian.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "repo-guardian.labels" . | nindent 4 }}
type: Opaque
stringData:
  app-id: {{ required "config.appId is required" .Values.config.appId | quote }}
  webhook-secret: {{ required "secrets.webhookSecret is required" .Values.secrets.webhookSecret | quote }}
  {{- if .Values.secrets.privateKey }}
  private-key: |
    {{- .Values.secrets.privateKey | nindent 4 }}
  {{- end }}
{{- end }}
