// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/donaldgifford/repo-guardian/internal/queue"
	mock "github.com/stretchr/testify/mock"
)

// NewMockQueue creates a new instance of MockQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueue {
	mock := &MockQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueue is an autogenerated mock type for the Queue type
type MockQueue struct {
	mock.Mock
}

type MockQueue_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueue) EXPECT() *MockQueue_Expecter {
	return &MockQueue_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockQueue
func (_mock *MockQueue) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueue_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockQueue_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockQueue_Expecter) Close() *MockQueue_Close_Call {
	return &MockQueue_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockQueue_Close_Call) Run(run func()) *MockQueue_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueue_Close_Call) Return(err error) *MockQueue_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueue_Close_Call) RunAndReturn(run func() error) *MockQueue_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Enqueue provides a mock function for the type MockQueue
func (_mock *MockQueue) Enqueue(ctx context.Context, j queue.Job) error {
	ret := _mock.Called(ctx, j)

	if len(ret) == 0 {
		panic("no return value specified for Enqueue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, queue.Job) error); ok {
		r0 = returnFunc(ctx, j)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueue_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type MockQueue_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - ctx context.Context
//   - j queue.Job
func (_e *MockQueue_Expecter) Enqueue(ctx any, j any) *MockQueue_Enqueue_Call {
	return &MockQueue_Enqueue_Call{Call: _e.mock.On("Enqueue", ctx, j)}
}

func (_c *MockQueue_Enqueue_Call) Run(run func(ctx context.Context, j queue.Job)) *MockQueue_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 queue.Job
		if args[1] != nil {
			arg1 = args[1].(queue.Job)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueue_Enqueue_Call) Return(err error) *MockQueue_Enqueue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueue_Enqueue_Call) RunAndReturn(run func(ctx context.Context, j queue.Job) error) *MockQueue_Enqueue_Call {
	_c.Call.Return(run)
	return _c
}

// EnqueueAfter provides a mock function for the type MockQueue
func (_mock *MockQueue) EnqueueAfter(ctx context.Context, j queue.Job, at time.Time) error {
	ret := _mock.Called(ctx, j, at)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueAfter")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, queue.Job, time.Time) error); ok {
		r0 = returnFunc(ctx, j, at)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueue_EnqueueAfter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueAfter'
type MockQueue_EnqueueAfter_Call struct {
	*mock.Call
}

// EnqueueAfter is a helper method to define mock.On call
//   - ctx context.Context
//   - j queue.Job
//   - at time.Time
func (_e *MockQueue_Expecter) EnqueueAfter(ctx any, j any, at any) *MockQueue_EnqueueAfter_Call {
	return &MockQueue_EnqueueAfter_Call{Call: _e.mock.On("EnqueueAfter", ctx, j, at)}
}

func (_c *MockQueue_EnqueueAfter_Call) Run(run func(ctx context.Context, j queue.Job, at time.Time)) *MockQueue_EnqueueAfter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 queue.Job
		if args[1] != nil {
			arg1 = args[1].(queue.Job)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueue_EnqueueAfter_Call) Return(err error) *MockQueue_EnqueueAfter_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueue_EnqueueAfter_Call) RunAndReturn(run func(ctx context.Context, j queue.Job, at time.Time) error) *MockQueue_EnqueueAfter_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type MockQueue
func (_mock *MockQueue) Subscribe(ctx context.Context, handler func(context.Context, queue.Job) error) error {
	ret := _mock.Called(ctx, handler)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(context.Context, queue.Job) error) error); ok {
		r0 = returnFunc(ctx, handler)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueue_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockQueue_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - handler func(context.Context, queue.Job) error
func (_e *MockQueue_Expecter) Subscribe(ctx any, handler any) *MockQueue_Subscribe_Call {
	return &MockQueue_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, handler)}
}

func (_c *MockQueue_Subscribe_Call) Run(run func(ctx context.Context, handler func(context.Context, queue.Job) error)) *MockQueue_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(context.Context, queue.Job) error
		if args[1] != nil {
			arg1 = args[1].(func(context.Context, queue.Job) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueue_Subscribe_Call) Return(err error) *MockQueue_Subscribe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueue_Subscribe_Call) RunAndReturn(run func(ctx context.Context, handler func(context.Context, queue.Job) error) error) *MockQueue_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}
