// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	queue "github.com/donaldgifford/repo-guardian/internal/queue"
	mock "github.com/stretchr/testify/mock"
)

// MockQueue is an autogenerated mock type for the Queue type
type MockQueue struct {
	mock.Mock
}

type MockQueue_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueue) EXPECT() *MockQueue_Expecter {
	return &MockQueue_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockQueue) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQueue_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockQueue_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockQueue_Expecter) Close() *MockQueue_Close_Call {
	return &MockQueue_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockQueue_Close_Call) Run(run func()) *MockQueue_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueue_Close_Call) Return(_a0 error) *MockQueue_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQueue_Close_Call) RunAndReturn(run func() error) *MockQueue_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Enqueue provides a mock function with given fields: ctx, j
func (_m *MockQueue) Enqueue(ctx context.Context, j queue.Job) error {
	ret := _m.Called(ctx, j)

	if len(ret) == 0 {
		panic("no return value specified for Enqueue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, queue.Job) error); ok {
		r0 = rf(ctx, j)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQueue_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type MockQueue_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - ctx context.Context
//   - j queue.Job
func (_e *MockQueue_Expecter) Enqueue(ctx interface{}, j interface{}) *MockQueue_Enqueue_Call {
	return &MockQueue_Enqueue_Call{Call: _e.mock.On("Enqueue", ctx, j)}
}

func (_c *MockQueue_Enqueue_Call) Run(run func(ctx context.Context, j queue.Job)) *MockQueue_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(queue.Job))
	})
	return _c
}

func (_c *MockQueue_Enqueue_Call) Return(_a0 error) *MockQueue_Enqueue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQueue_Enqueue_Call) RunAndReturn(run func(context.Context, queue.Job) error) *MockQueue_Enqueue_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: ctx, handler
func (_m *MockQueue) Subscribe(ctx context.Context, handler func(context.Context, queue.Job) error) error {
	ret := _m.Called(ctx, handler)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context, queue.Job) error) error); ok {
		r0 = rf(ctx, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQueue_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockQueue_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - handler func(context.Context , queue.Job) error
func (_e *MockQueue_Expecter) Subscribe(ctx interface{}, handler interface{}) *MockQueue_Subscribe_Call {
	return &MockQueue_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, handler)}
}

func (_c *MockQueue_Subscribe_Call) Run(run func(ctx context.Context, handler func(context.Context, queue.Job) error)) *MockQueue_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context, queue.Job) error))
	})
	return _c
}

func (_c *MockQueue_Subscribe_Call) Return(_a0 error) *MockQueue_Subscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQueue_Subscribe_Call) RunAndReturn(run func(context.Context, func(context.Context, queue.Job) error) error) *MockQueue_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueue creates a new instance of MockQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueue {
	mock := &MockQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
